"""ADR-0210: Unified Initial Analysis (Phase 1).

Single LM call that replaces 4 sequential calls: classification + entity extraction
+ routing + planning. Reduces token cost 56% and latency 50% by batching structural
decisions upfront.

Sent as a structured LM call early in request processing; cached for the lifetime
of that task (5 min TTL). All downstream execution steps reuse the cached decision,
preventing re-planning in each step.

CI lint: module MUST NOT import anthropic.
"""
from __future__ import annotations

import json
import time
from dataclasses import asdict, dataclass, field
from typing import Any

# ── Server-side plan bounds (ADR-0217 hardening, 2026-07-24) ──────────────────
# The global plan comes from an LM whose input (the task text) is untrusted and
# prompt-injectable. Without a ceiling, an injected "plan 300 fully-parallel
# steps, estimated_tokens 10**12" response would spawn hundreds of concurrent
# claude-CLI subprocesses and self-authorize an effectively infinite budget —
# all for ONE charged pool unit (adversarial review HIGH). These caps validate
# the untrusted output at the deserialization boundary, the structurally
# correct place. A plan exceeding MAX_PLAN_STEPS is REJECTED (ValueError →
# clean error turn + quota refund); per-field integer estimates are coerced and
# clamped rather than trusted verbatim.
MAX_PLAN_STEPS = 64
MAX_ESTIMATED_TOKENS = 5_000_000
MAX_STEP_ESTIMATED_TOKENS = 500_000
MAX_ESTIMATED_DURATION_S = 24 * 3600


def _clamp_int(value: Any, default: int, lo: int, hi: int) -> int:
    """Coerce an untrusted LM value to an int in [lo, hi]; default on garbage."""
    try:
        n = int(value)
    except (TypeError, ValueError):
        return default
    return max(lo, min(hi, n))


@dataclass
class Step:
    """Single execution step from the global plan."""
    step: int                      # Sequential step number
    action: str                    # "read_file" | "call_tool" | "analyze_data" | etc
    depends_on: list[int] = field(default_factory=list)  # Step numbers this depends on
    can_parallelize: list[int] = field(default_factory=list)  # Step numbers safe to run in parallel
    estimated_tokens: int = 5000   # Rough estimate for billing/planning
    # WHAT to actually do (target file, content spec, tool + args). Without
    # this an executor only sees the bare action enum and cannot perform the
    # step — found via live E2E 2026-07-23 (ADR-0214 review).
    description: str = ""


@dataclass
class GlobalPlan:
    """Overall execution plan with parallelization hints."""
    steps: list[Step]                  # Ordered list of execution steps
    estimated_duration_s: int          # Total estimated wall time
    estimated_tokens: int              # Total estimated token consumption
    fallback_strategy: str = "sequential"  # Fallback if parallel fails — NOT the mode selector (can_parallelize hints opt steps into batching)


@dataclass
class Classification:
    """Task classification from initial analysis."""
    task_type: str                 # "code_generation" | "data_analysis" | "tool_call" | ...
    complexity: str                # "simple" | "moderate" | "complex"
    engine_preference: str         # "claude" | "gemini" | "local" | "default"
    confidence: float              # 0.0-1.0, routing confidence


@dataclass
class Entities:
    """Extracted entities (files, tools, APIs, environment vars)."""
    files: list[dict] = field(default_factory=list)        # {path, purpose}
    tools: list[str] = field(default_factory=list)         # Tool names
    external_apis: list[str] = field(default_factory=list)  # API names
    environment_vars: list[str] = field(default_factory=list)  # Var names


@dataclass
class InitialAnalysisRequest:
    """Replaces 4 sequential LM calls: classify + extract + route + plan.

    Generated by a single LM call at the start of task processing. Cached
    for reuse across all downstream execution steps. All routing, planning,
    and entity extraction happens ONCE in this call; no re-planning in steps.
    """
    classification: Classification
    entities: Entities
    global_plan: GlobalPlan

    # Cache metadata
    cache_key: str = ""              # hash(task) for reuse
    ttl_seconds: int = 300            # 5 min TTL (5*60)
    created_at: float = field(default_factory=time.time)


    def to_dict(self) -> dict[str, Any]:
        """Serialize to dict for JSON storage."""
        return {
            "classification": asdict(self.classification),
            "entities": asdict(self.entities),
            "global_plan": {
                "steps": [asdict(s) for s in self.global_plan.steps],
                "estimated_duration_s": self.global_plan.estimated_duration_s,
                "estimated_tokens": self.global_plan.estimated_tokens,
                "fallback_strategy": self.global_plan.fallback_strategy,
            },
            "cache_key": self.cache_key,
            "ttl_seconds": self.ttl_seconds,
            "created_at": self.created_at,
        }

    @staticmethod
    def from_dict(d: dict[str, Any]) -> InitialAnalysisRequest:
        """Deserialize from dict.

        Tolerant against EXTRA keys (LMs routinely add e.g. a step
        "description" despite the schema) — unknown keys are dropped.
        Missing REQUIRED fields still raise (strict where it matters).
        """
        import dataclasses

        def _known(cls: Any, data: dict[str, Any]) -> dict[str, Any]:
            # Drop unknown keys AND explicit nulls: an LM-emitted
            # `"description": null` must fall back to the field default
            # instead of poisoning downstream str-operations with None.
            names = {f.name for f in dataclasses.fields(cls)}
            return {k: v for k, v in data.items() if k in names and v is not None}

        raw_steps = d["global_plan"]["steps"]
        # Cap total plan size BEFORE constructing steps — reject, don't
        # silently truncate (dropping steps would produce a subtly-wrong run).
        # Rejection here raises during analysis parsing, BEFORE any pool unit
        # is charged (the charge happens later in engine.execute), so there is
        # nothing to refund — the turn simply degrades to an error result.
        if not isinstance(raw_steps, list):
            raise ValueError("global_plan.steps must be a list")
        if len(raw_steps) > MAX_PLAN_STEPS:
            raise ValueError(
                f"plan too large: {len(raw_steps)} steps exceeds cap "
                f"{MAX_PLAN_STEPS} (untrusted-plan guard)"
            )

        steps: list[Step] = []
        for s in raw_steps:
            known = _known(Step, s)
            # Clamp the per-step token estimate so a single step can't
            # self-authorize a runaway budget (see _clamp_int / the module caps).
            if "estimated_tokens" in known:
                known["estimated_tokens"] = _clamp_int(
                    known["estimated_tokens"], 5000, 0, MAX_STEP_ESTIMATED_TOKENS)
            steps.append(Step(**known))

        return InitialAnalysisRequest(
            classification=Classification(**_known(Classification, d["classification"])),
            entities=Entities(**_known(Entities, d["entities"])),
            global_plan=GlobalPlan(
                steps=steps,
                estimated_duration_s=_clamp_int(
                    d["global_plan"]["estimated_duration_s"], 60, 0,
                    MAX_ESTIMATED_DURATION_S),
                estimated_tokens=_clamp_int(
                    d["global_plan"]["estimated_tokens"], 30_000, 0,
                    MAX_ESTIMATED_TOKENS),
                fallback_strategy=d["global_plan"].get("fallback_strategy", "sequential"),
            ),
            cache_key=d.get("cache_key", ""),
            ttl_seconds=d.get("ttl_seconds", 300),
            created_at=d.get("created_at", time.time()),
        )


# ── Task Analysis Prompt Template ──────────────────────────────────────────

TASK_ANALYSIS_PROMPT_TEMPLATE = """You are a task analysis engine for an AI orchestration system. Your job is to analyze a user request COMPLETELY in one pass, answering all structural questions upfront so downstream execution steps can proceed without re-planning.

Input:
- **Task:** {task_description}
- **Context:** {context_json}

Your analysis MUST output a JSON object with three sections:

## 1. Classification

Analyze the task type, complexity, and routing:
- **task_type**: One of: code_generation, data_analysis, tool_call, reasoning, transformation, retrieval, delegation. Choose the primary type; your confidence drives routing.
- **complexity**: simple (single LM call), moderate (2-3 steps), complex (4+ steps).
- **engine_preference**: claude (best for reasoning/planning), gemini (fast), local (privacy), default (auto).
- **confidence**: 0.0-1.0. Low confidence (< 0.7) flags uncertain routing; routing may need fallback.

## 2. Entity Extraction

Identify all external dependencies:
- **files**: [{{path: str, purpose: "input" | "output" | "reference"}}]
- **tools**: ["tool1", "tool2"] — tools the task will call
- **external_apis**: ["api1"] — external services (HTTP, database, etc.)
- **environment_vars**: ["VAR1", "VAR2"] — env vars this task depends on

## 3. Global Execution Plan

Design the full step sequence with parallelization hints:
- **steps**: [
    {{
      "step": 1,
      "action": one of "read_file" | "write_file" | "call_tool" | "api_fetch" | "database_query" | "list_files" | "check_existence" | "analyze_data" | "reason_about" | "generate_code" | "generate_text" | "generate_report" | "synthesize" | "evaluate",
      "description": "concrete instruction: WHAT to do, which file/target, expected output — an executor must be able to perform the step from this text alone",
      "depends_on": [list of step numbers],
      "can_parallelize": [list of step numbers that can run in parallel with this one],
      "estimated_tokens": integer (rough estimate)
    }},
    ...
  ]
- **estimated_duration_s**: total wall time (sum of longest chains, considering parallelism)
- **estimated_tokens**: total LM tokens for this task
- **fallback_strategy**: what to do when parallel execution FAILS: "sequential" (default) re-runs one-by-one. This is NOT the mode selector — parallel batching is opted into per step via `can_parallelize` hints (symmetric: both steps must list each other).

## JSON Output Format

Output ONLY a valid JSON object (no markdown, no preamble):

{{
  "classification": {{
    "task_type": "...",
    "complexity": "...",
    "engine_preference": "...",
    "confidence": 0.8
  }},
  "entities": {{
    "files": [...],
    "tools": [...],
    "external_apis": [...],
    "environment_vars": [...]
  }},
  "global_plan": {{
    "steps": [...],
    "estimated_duration_s": ...,
    "estimated_tokens": ...,
    "fallback_strategy": "..."
  }}
}}

## Critical Rules

1. **Completeness:** Your output is used by ALL downstream steps. Missing decisions = execution failure. Be thorough.
2. **No Re-Planning:** Downstream steps WILL NOT call you again. Encode all routing, classification, and planning in this ONE response.
3. **Parallelization:** Use can_parallelize hints to unlock wall-clock speedup. Mark steps that genuinely have no dependencies on each other.
4. **Accuracy:** Estimate step counts realistically. Keep the plan to at most 64 steps (a hard server cap — larger plans are rejected). Decompose only as far as the task genuinely needs; do not pad.
5. **Realism:** Tokens and duration are hints, not hard limits. Measure actual during execution, but be honest here.

Analysis complete. Output the JSON object now."""


def make_task_analysis_prompt(
    task_description: str,
    context: dict[str, Any] | None = None,
) -> str:
    """Build a task analysis prompt from the template.

    Args:
        task_description: Plain English task description (2-200 words)
        context: Optional dict with task context (file state, prior results, config, etc.)

    Returns:
        Filled-in prompt string ready to send to LM.
    """
    if context is None:
        context = {}

    context_json = json.dumps(context, indent=2, default=str)
    prompt = TASK_ANALYSIS_PROMPT_TEMPLATE.format(
        task_description=task_description,
        context_json=context_json,
    )
    return prompt


def parse_task_analysis_response(lm_response: str) -> InitialAnalysisRequest:
    """Parse an LM response to InitialAnalysisRequest.

    Args:
        lm_response: Raw LM output (hopefully JSON, but may have wrapping text).

    Returns:
        Parsed InitialAnalysisRequest.

    Raises:
        ValueError: If response is not valid JSON or missing required fields.
    """
    # Try to extract JSON from the response (in case LM added preamble/postamble)
    try:
        data = json.loads(lm_response)
    except json.JSONDecodeError:
        # Try to find JSON block inside markdown code fence.
        # Use non-greedy {.*?} to capture first JSON block (prevent multi-JSON confusion).
        import re
        match = re.search(r"```(?:json)?\s*(\{.*?\})\s*```", lm_response, re.DOTALL)
        if match:
            try:
                data = json.loads(match.group(1))
            except json.JSONDecodeError:
                raise ValueError(f"Markdown JSON block is not valid: {match.group(1)[:200]}")
        else:
            raise ValueError(f"Response is not valid JSON: {lm_response[:200]}")

    # Validate required fields
    required = {"classification", "entities", "global_plan"}
    if not all(k in data for k in required):
        raise ValueError(f"Missing required fields: {required - set(data.keys())}")

    return InitialAnalysisRequest.from_dict(data)
