"""ADR-0210: Unified Initial Analysis (Phase 1).

Single LM call that replaces 4 sequential calls: classification + entity extraction
+ routing + planning. Reduces token cost 56% and latency 50% by batching structural
decisions upfront.

Sent as a structured LM call early in request processing; cached for the lifetime
of that task (5 min TTL). All downstream execution steps reuse the cached decision,
preventing re-planning in each step.

CI lint: module MUST NOT import anthropic.
"""
from __future__ import annotations

import hashlib
import json
import time
from dataclasses import dataclass, field, asdict
from typing import Any, Optional


@dataclass
class Step:
    """Single execution step from the global plan."""
    step: int                      # Sequential step number
    action: str                    # "read_file" | "call_tool" | "analyze_data" | etc
    depends_on: list[int] = field(default_factory=list)  # Step numbers this depends on
    can_parallelize: list[int] = field(default_factory=list)  # Step numbers safe to run in parallel
    estimated_tokens: int = 5000   # Rough estimate for billing/planning


@dataclass
class GlobalPlan:
    """Overall execution plan with parallelization hints."""
    steps: list[Step]                  # Ordered list of execution steps
    estimated_duration_s: int          # Total estimated wall time
    estimated_tokens: int              # Total estimated token consumption
    fallback_strategy: str = "sequential"  # Fallback if parallel fails


@dataclass
class Classification:
    """Task classification from initial analysis."""
    task_type: str                 # "code_generation" | "data_analysis" | "tool_call" | ...
    complexity: str                # "simple" | "moderate" | "complex"
    engine_preference: str         # "claude" | "gemini" | "local" | "default"
    confidence: float              # 0.0-1.0, routing confidence


@dataclass
class Entities:
    """Extracted entities (files, tools, APIs, environment vars)."""
    files: list[dict] = field(default_factory=list)        # {path, purpose}
    tools: list[str] = field(default_factory=list)         # Tool names
    external_apis: list[str] = field(default_factory=list)  # API names
    environment_vars: list[str] = field(default_factory=list)  # Var names


@dataclass
class InitialAnalysisRequest:
    """Replaces 4 sequential LM calls: classify + extract + route + plan.

    Generated by a single LM call at the start of task processing. Cached
    for reuse across all downstream execution steps. All routing, planning,
    and entity extraction happens ONCE in this call; no re-planning in steps.
    """
    classification: Classification
    entities: Entities
    global_plan: GlobalPlan

    # Cache metadata
    cache_key: str = ""              # hash(task) for reuse
    ttl_seconds: int = 300            # 5 min TTL (5*60)
    created_at: float = field(default_factory=time.time)


    def to_dict(self) -> dict[str, Any]:
        """Serialize to dict for JSON storage."""
        return {
            "classification": asdict(self.classification),
            "entities": asdict(self.entities),
            "global_plan": {
                "steps": [asdict(s) for s in self.global_plan.steps],
                "estimated_duration_s": self.global_plan.estimated_duration_s,
                "estimated_tokens": self.global_plan.estimated_tokens,
                "fallback_strategy": self.global_plan.fallback_strategy,
            },
            "cache_key": self.cache_key,
            "ttl_seconds": self.ttl_seconds,
            "created_at": self.created_at,
        }

    @staticmethod
    def from_dict(d: dict[str, Any]) -> InitialAnalysisRequest:
        """Deserialize from dict."""
        return InitialAnalysisRequest(
            classification=Classification(**d["classification"]),
            entities=Entities(**d["entities"]),
            global_plan=GlobalPlan(
                steps=[Step(**s) for s in d["global_plan"]["steps"]],
                estimated_duration_s=d["global_plan"]["estimated_duration_s"],
                estimated_tokens=d["global_plan"]["estimated_tokens"],
                fallback_strategy=d["global_plan"].get("fallback_strategy", "sequential"),
            ),
            cache_key=d.get("cache_key", ""),
            ttl_seconds=d.get("ttl_seconds", 300),
            created_at=d.get("created_at", time.time()),
        )


# ── Task Analysis Prompt Template ──────────────────────────────────────────

TASK_ANALYSIS_PROMPT_TEMPLATE = """You are a task analysis engine for an AI orchestration system. Your job is to analyze a user request COMPLETELY in one pass, answering all structural questions upfront so downstream execution steps can proceed without re-planning.

Input:
- **Task:** {task_description}
- **Context:** {context_json}

Your analysis MUST output a JSON object with three sections:

## 1. Classification

Analyze the task type, complexity, and routing:
- **task_type**: One of: code_generation, data_analysis, tool_call, reasoning, transformation, retrieval, delegation. Choose the primary type; your confidence drives routing.
- **complexity**: simple (single LM call), moderate (2-3 steps), complex (4+ steps).
- **engine_preference**: claude (best for reasoning/planning), gemini (fast), local (privacy), default (auto).
- **confidence**: 0.0-1.0. Low confidence (< 0.7) flags uncertain routing; routing may need fallback.

## 2. Entity Extraction

Identify all external dependencies:
- **files**: [{path: str, purpose: "input" | "output" | "reference"}]
- **tools**: ["tool1", "tool2"] — tools the task will call
- **external_apis**: ["api1"] — external services (HTTP, database, etc.)
- **environment_vars**: ["VAR1", "VAR2"] — env vars this task depends on

## 3. Global Execution Plan

Design the full step sequence with parallelization hints:
- **steps**: [
    {{
      "step": 1,
      "action": "read_file" | "call_tool" | "analyze_data" | "generate_code" | "api_fetch",
      "depends_on": [list of step numbers],
      "can_parallelize": [list of step numbers that can run in parallel with this one],
      "estimated_tokens": integer (rough estimate)
    }},
    ...
  ]
- **estimated_duration_s**: total wall time (sum of longest chains, considering parallelism)
- **estimated_tokens**: total LM tokens for this task
- **fallback_strategy**: "sequential" (default; run steps one-by-one) or "parallel" (try groups in parallel)

## JSON Output Format

Output ONLY a valid JSON object (no markdown, no preamble):

{{
  "classification": {{
    "task_type": "...",
    "complexity": "...",
    "engine_preference": "...",
    "confidence": 0.8
  }},
  "entities": {{
    "files": [...],
    "tools": [...],
    "external_apis": [...],
    "environment_vars": [...]
  }},
  "global_plan": {{
    "steps": [...],
    "estimated_duration_s": ...,
    "estimated_tokens": ...,
    "fallback_strategy": "..."
  }}
}}

## Critical Rules

1. **Completeness:** Your output is used by ALL downstream steps. Missing decisions = execution failure. Be thorough.
2. **No Re-Planning:** Downstream steps WILL NOT call you again. Encode all routing, classification, and planning in this ONE response.
3. **Parallelization:** Use can_parallelize hints to unlock wall-clock speedup. Mark steps that genuinely have no dependencies on each other.
4. **Accuracy:** Estimate step counts realistically. A 50-step plan is fine; it's better to over-plan than under-plan.
5. **Realism:** Tokens and duration are hints, not hard limits. Measure actual during execution, but be honest here.

Analysis complete. Output the JSON object now."""


def make_task_analysis_prompt(
    task_description: str,
    context: dict[str, Any] | None = None,
) -> str:
    """Build a task analysis prompt from the template.

    Args:
        task_description: Plain English task description (2-200 words)
        context: Optional dict with task context (file state, prior results, config, etc.)

    Returns:
        Filled-in prompt string ready to send to LM.
    """
    if context is None:
        context = {}

    context_json = json.dumps(context, indent=2, default=str)
    prompt = TASK_ANALYSIS_PROMPT_TEMPLATE.format(
        task_description=task_description,
        context_json=context_json,
    )
    return prompt


def parse_task_analysis_response(lm_response: str) -> InitialAnalysisRequest:
    """Parse an LM response to InitialAnalysisRequest.

    Args:
        lm_response: Raw LM output (hopefully JSON, but may have wrapping text).

    Returns:
        Parsed InitialAnalysisRequest.

    Raises:
        ValueError: If response is not valid JSON or missing required fields.
    """
    # Try to extract JSON from the response (in case LM added preamble/postamble)
    try:
        data = json.loads(lm_response)
    except json.JSONDecodeError:
        # Try to find JSON block inside markdown code fence.
        # Use greedy {.*} to capture complete JSON, not partial structures.
        import re
        match = re.search(r"```(?:json)?\s*(\{.*\})\s*```", lm_response, re.DOTALL)
        if match:
            try:
                data = json.loads(match.group(1))
            except json.JSONDecodeError:
                raise ValueError(f"Markdown JSON block is not valid: {match.group(1)[:200]}")
        else:
            raise ValueError(f"Response is not valid JSON: {lm_response[:200]}")

    # Validate required fields
    required = {"classification", "entities", "global_plan"}
    if not all(k in data for k in required):
        raise ValueError(f"Missing required fields: {required - set(data.keys())}")

    return InitialAnalysisRequest.from_dict(data)
