"""Plugin ADR generator (ADR-0253 Phase 4 artifact #3).

Produces a small, plugin-scoped ADR in this repo's own ADR shape (Context /
Decision / Alternatives / Consequences) — NOT a CorvinOS-repo ADR. It documents
one decision: why this plugin idea was classified the way it was. It is meant
to travel with the plugin's own repo, not to be filed in `Corvin-ADR/`.
"""
from __future__ import annotations

from ..models import Classification, PluginIdea

_KIND_ALTERNATIVES = {
    "mcp_server": (
        "A Skill (no code, can't call external tools) — rejected, the "
        "problem needs executable behaviour. A Provider plugin — rejected, "
        "this isn't one of the 11 known in-process capability types."
    ),
    "skill": (
        "An MCP server or Hook (both need executable code and a Tier B/C "
        "license slot) — rejected, the interview answers describe "
        "instructions/guidance, not a program."
    ),
    "hook": (
        "A full Provider plugin replacing a component — rejected, the goal "
        "is to customise ONE step of an existing default, not own the whole "
        "decision (ADR-0237 hook vs. replace)."
    ),
    "provider": (
        "An Integration outside the plugin registry — rejected, the "
        "interview answers matched an existing `KNOWN_PLUGIN_TYPES` entry "
        "closely enough to use the real capability protocol instead of a "
        "bespoke one."
    ),
    "integration": (
        "A Provider plugin against a specific known type — considered, but "
        "the interview answers did not match any of the 11 types with "
        "enough confidence to commit to one; review before building."
    ),
    "custom": (
        "Every known kind — none matched. This is not a rejection of any "
        "one alternative, it is an absence of signal; resolve with a "
        "maintainer conversation, not by picking the closest guess."
    ),
}


def generate_adr_doc(idea: PluginIdea, classification: Classification, plugin_id: str) -> str:
    c = classification
    lines = [
        f"# ADR: {idea.plugin_name} — Plugin Classification",
        "",
        "**Status:** PROPOSED (generated, needs human review)",
        f"**Generated by:** Plugin-Builder (ADR-0253), confidence {c.confidence:.0%}",
        "",
        "## Context",
        "",
        idea.problem.problem,
        "",
        f"Target audience: {idea.problem.target_audience}",
        "",
        "## Decision",
        "",
        f"Build `{plugin_id}` as a **{c.kind.value}** plugin, Tier {c.tier.value} "
        "(ADR-0156).",
    ]
    if c.plugin_type:
        lines.append(f"Plugin type: `{c.plugin_type}` (`KNOWN_PLUGIN_TYPES`).")
    if c.extension_point:
        lines.append(f"Extension point: `{c.extension_point}`.")
    lines += [
        "",
        f"Rationale: {c.rationale}",
        "",
        "## Alternatives",
        "",
        _KIND_ALTERNATIVES.get(c.kind.value, "Not enumerated for this kind."),
        "",
        "## Consequences",
        "",
    ]
    if c.risk_flags:
        for flag in c.risk_flags:
            lines.append(f"- ⚠ {flag}")
    else:
        lines.append("- No risks were surfaced by the classifier for this idea.")
    lines += [
        "",
        "## Related",
        "",
        "- ADR-0244–0251 (plugin taxonomy, template contract, security model)",
        "- ADR-0156 (Tier A/B/C capability boundary)",
        "- ADR-0253 (Plugin-Builder Framework — generated this document)",
        "",
        "## Sign-off",
        "",
        "This ADR was generated, not authored. Treat it as a first draft: "
        "confirm the classification is right, and edit before it ships with "
        "the plugin.",
        "",
    ]
    return "\n".join(lines)


__all__ = ["generate_adr_doc"]
