"""Plugin ADR generator (ADR-0253 Phase 4 artifact #3).

Produces a small, plugin-scoped ADR in this repo's own ADR shape (Context /
Decision / Alternatives / Consequences) — NOT a CorvinOS-repo ADR. It documents
one decision: why this plugin idea was classified the way it was. It is meant
to travel with the plugin's own repo, not to be filed in `Corvin-ADR/`.

Carries ADR-0264 frontmatter (id/status/depends_on/related/paths/docs) like
every CorvinOS-repo ADR written after that convention, even though this
document lives outside `Corvin-ADR/decisions/` and outside
`scripts/adr_graph.py`'s default search path: the schema is what makes an ADR
machine-traversable, not its filing location, and a plugin's own generated
ADR is exactly the kind of node a coding agent working inside that plugin's
repo should be able to enter the graph from. `id` is plugin-scoped
(`{plugin_id}-ADR-0001`, not a Corvin-ADR sequence number) since a plugin may
accumulate more than one generated ADR over its life without colliding with
this repo's numbering. `related` points INTO the real Corvin-ADR corpus
(ADR-0253, ADR-0156, the taxonomy ADRs) — cross-repo edges are allowed by
design (ADR-0264 "Decision" §1: paths/edges are not required to resolve
locally to be meaningful). `docs:` points at this ADR's own SIBLING generated
docs (`plugin-idea.md`, `plugin-architecture.md`, `build-plan.md` — see
generators/scaffold.py's `doc_sources`), the concrete three-layer example
ADR-0264's second amendment describes: the generated code scaffold, these
generated docs, and this generated ADR all cross-reference one plugin's single
classification decision.
"""
from __future__ import annotations

from ..models import Classification, PluginIdea

_KIND_ALTERNATIVES = {
    "mcp_server": (
        "A Skill (no code, can't call external tools) — rejected, the "
        "problem needs executable behaviour. A Provider plugin — rejected, "
        "this isn't one of the 11 known in-process capability types."
    ),
    "skill": (
        "An MCP server or Hook (both need executable code and a Tier B/C "
        "license slot) — rejected, the interview answers describe "
        "instructions/guidance, not a program."
    ),
    "hook": (
        "A full Provider plugin replacing a component — rejected, the goal "
        "is to customise ONE step of an existing default, not own the whole "
        "decision (ADR-0237 hook vs. replace)."
    ),
    "provider": (
        "An Integration outside the plugin registry — rejected, the "
        "interview answers matched an existing `KNOWN_PLUGIN_TYPES` entry "
        "closely enough to use the real capability protocol instead of a "
        "bespoke one."
    ),
    "integration": (
        "A Provider plugin against a specific known type — considered, but "
        "the interview answers did not match any of the 11 types with "
        "enough confidence to commit to one; review before building."
    ),
    "custom": (
        "Every known kind — none matched. This is not a rejection of any "
        "one alternative, it is an absence of signal; resolve with a "
        "maintainer conversation, not by picking the closest guess."
    ),
}


_RELATED_ADRS = ("ADR-0244", "ADR-0245", "ADR-0246", "ADR-0247", "ADR-0248",
                  "ADR-0249", "ADR-0250", "ADR-0251", "ADR-0156", "ADR-0253")


_SIBLING_DOCS = ("plugin-idea.md", "plugin-architecture.md", "build-plan.md")


def _adr_frontmatter(plugin_id: str) -> list[str]:
    """ADR-0264 schema — see module docstring for why a plugin-scoped
    generated ADR carries it even though it is filed outside Corvin-ADR/.

    `docs:` names its sibling generated docs (relative to the shared
    `docs/` dir all four generators write into, see generators/scaffold.py)
    -- the concrete three-layer example ADR-0264's second amendment
    describes: generated code, generated docs, and this generated ADR all
    cross-reference the same classification decision.
    """
    related = ", ".join(_RELATED_ADRS)
    lines = [
        "---",
        f"id: {plugin_id}-ADR-0001",
        "status: proposed",
        "supersedes: []",
        "depends_on: []",
        f"related: [{related}]",
        "commits: []",
        "paths:",
        '  - "**"',
        "docs:",
    ]
    lines += [f'  - "{name}"' for name in _SIBLING_DOCS]
    lines += ["---", ""]
    return lines


def generate_adr_doc(idea: PluginIdea, classification: Classification, plugin_id: str) -> str:
    c = classification
    lines = _adr_frontmatter(plugin_id) + [
        f"# ADR: {idea.plugin_name} — Plugin Classification",
        "",
        "**Status:** PROPOSED (generated, needs human review)",
        f"**Generated by:** Plugin-Builder (ADR-0253), confidence {c.confidence:.0%}",
        "",
        "## Context",
        "",
        idea.problem.problem,
        "",
        f"Target audience: {idea.problem.target_audience}",
        "",
        "## Decision",
        "",
        f"Build `{plugin_id}` as a **{c.kind.value}** plugin, Tier {c.tier.value} "
        "(ADR-0156).",
    ]
    if c.plugin_type:
        lines.append(f"Plugin type: `{c.plugin_type}` (`KNOWN_PLUGIN_TYPES`).")
    if c.extension_point:
        lines.append(f"Extension point: `{c.extension_point}`.")
    lines += [
        "",
        f"Rationale: {c.rationale}",
        "",
        "## Alternatives",
        "",
        _KIND_ALTERNATIVES.get(c.kind.value, "Not enumerated for this kind."),
        "",
        "## Consequences",
        "",
    ]
    if c.risk_flags:
        for flag in c.risk_flags:
            lines.append(f"- ⚠ {flag}")
    else:
        lines.append("- No risks were surfaced by the classifier for this idea.")
    lines += [
        "",
        "## Related",
        "",
        "- ADR-0244–0251 (plugin taxonomy, template contract, security model)",
        "- ADR-0156 (Tier A/B/C capability boundary)",
        "- ADR-0253 (Plugin-Builder Framework — generated this document)",
        "",
        "## Sign-off",
        "",
        "This ADR was generated, not authored. Treat it as a first draft: "
        "confirm the classification is right, and edit before it ships with "
        "the plugin.",
        "",
    ]
    return "\n".join(lines)


__all__ = ["generate_adr_doc"]
