"""Architecture Concept generator (ADR-0253 Phase 4 artifact #2)."""
from __future__ import annotations

from ..models import Classification, PluginIdea, PluginKind

_TIER_SECURITY_NOTE = {
    "A": (
        "Tier A (prompt-only): no executable code runs from this plugin. The "
        "security boundary is the same one every SkillForge skill already has "
        "— it is instructions an engine reads, not a program it runs."
    ),
    "B": (
        "Tier B (sandboxed compute): runs bwrap-isolated (ADR-0069), same "
        "sandbox as a Forge tool. L10 path-gate applies to any filesystem "
        "access. The free license tier allows only ONE active executable "
        "layer (Tier B or C) at a time — confirm this is the intended slot."
    ),
    "C": (
        "Tier C (subprocess protocol): runs OUT of process as its own MCP "
        "server, reached over stdio JSON-RPC. L10/L34/L35 gates apply at every "
        "spawn. The free license tier allows only ONE active executable layer "
        "(Tier B or C) at a time — confirm this is the intended slot."
    ),
}

_KIND_COMPONENTS = {
    PluginKind.MCP_SERVER: (
        "- A standalone subprocess exposing one or more MCP tools over "
        "stdio JSON-RPC (see `templates/mcp_server_plugin.py`).\n"
        "- No `corvin_plugins` registration — an MCP server is reached "
        "through the MCP client that spawns it, not through the in-process "
        "plugin registry."
    ),
    PluginKind.SKILL: (
        "- A single Markdown file (`skill_plugin.md`), prompt-injected into "
        "a turn when its trigger condition matches.\n"
        "- No runtime component at all — the \"architecture\" is the "
        "instruction text itself."
    ),
    PluginKind.HOOK: (
        "- A `CorvinPlugin` whose `on_load()` registers a callback on one "
        "`corvin_plugins.extension_points` point.\n"
        "- The bundled reference implementation keeps running; this hook "
        "customises exactly one named step of it, and only when the "
        "`plugin_extension_points` feature flag is on."
    ),
    PluginKind.PROVIDER: (
        "- A `CorvinPlugin` implementing one of the 11 `KNOWN_PLUGIN_TYPES` "
        "capability protocols.\n"
        "- `on_load()` registers itself with the matching `PluginContext` "
        "handle; the owning subsystem calls `get_active()` on that registry "
        "— check `corvin_plugins.surface_map` for whether anything does, "
        "for this specific type, in this build."
    ),
    PluginKind.INTEGRATION: (
        "- Talks to an external service or API. Likely implemented as a "
        "Provider plugin against the closest matching `KNOWN_PLUGIN_TYPES` "
        "entry — review the classification's `plugin_type` guess below."
    ),
    PluginKind.CUSTOM: (
        "- No architecture pattern in this codebase matches the interview "
        "answers closely enough to recommend one. This needs a maintainer "
        "conversation before an architecture can be proposed responsibly."
    ),
}


def generate_architecture_doc(idea: PluginIdea, classification: Classification) -> str:
    c = classification
    deps = idea.dependencies
    lines = [
        f"# Architecture Concept: {idea.plugin_name}",
        "",
        "> Generated by the Plugin-Builder (ADR-0253).",
        "",
        "## Components",
        "",
        _KIND_COMPONENTS[c.kind],
        "",
        "## Dataflow",
        "",
    ]
    if deps.requires_network_egress:
        hosts = ", ".join(deps.egress_hosts) or "(not specified — declare before shipping)"
        lines.append(f"- Talks to the network. Declared host(s): {hosts}.")
    else:
        lines.append("- No declared network egress — `network_egress: none` in the manifest.")
    if deps.requires_auth:
        lines.append(
            "- Requires authentication/credentials. Store them via the "
            "plugin's own config (`ctx.config`), never hard-coded, never "
            "logged."
        )
    if deps.external_libraries:
        lines.append(
            "- External dependencies: " + ", ".join(deps.external_libraries)
        )
    lines += [
        "",
        "## Security",
        "",
        f"- {_TIER_SECURITY_NOTE[c.tier.value]}",
        "- Manifest defaults to the least-privileged values: "
        "`layer: installed`, `origin: community`, `pii_risk: low`, "
        "`requires_consent: false` — raise any of these deliberately, with "
        "a stated reason, not by habit.",
    ]
    if c.risk_flags:
        lines.append("- Risks already surfaced by the classifier:")
        for flag in c.risk_flags:
            lines.append(f"  - ⚠ {flag}")
    lines += [
        "",
        "## Testing Strategy",
        "",
        "Follow the test pyramid (cheap → expensive; only escalate once the "
        "current tier is green):",
        "",
        "1. **Lint/type** — the scaffold as generated should pass `ruff` "
        "unmodified.",
        "2. **Unit** — the plugin's own logic, no `corvin_plugins` registry "
        "involved.",
    ]
    if c.kind == PluginKind.PROVIDER:
        lines.append(
            "3. **Integration** — `corvin plugin check <path>` (manifest + "
            "class conformance against the real registry, offline)."
        )
        lines.append(
            "4. **E2E** — load it into a real (test) registry via "
            "`corvin_plugins.bootstrap` and confirm the owning subsystem "
            "actually calls it — conformance is not the same as being "
            "consumed (ADR-0245)."
        )
    elif c.kind == PluginKind.HOOK:
        lines.append(
            "3. **Integration** — register the hook against a real "
            "`_ExtensionPointBus` (test isolation via `clear_all()`), turn "
            "`plugin_extension_points` on, and confirm `invoke()` reaches it."
        )
    elif c.kind == PluginKind.MCP_SERVER:
        lines.append(
            "3. **Integration** — feed `initialize` / `tools/list` / "
            "`tools/call` JSON-RPC requests to the subprocess over stdio and "
            "assert on the responses."
        )
    lines.append("")
    return "\n".join(lines)


__all__ = ["generate_architecture_doc"]
