"""Idea Document generator (ADR-0253 Phase 4 artifact #1)."""
from __future__ import annotations

from ..models import Classification, PluginIdea


def _success_criteria(idea: PluginIdea, c: Classification) -> list[str]:
    criteria = [
        "`corvin plugin check <path>` reports no errors against the generated manifest.",
        "The plugin loads and `health_check()` reports healthy in a real boot.",
    ]
    if c.plugin_type:
        criteria.append(
            f"The `{c.plugin_type}` capability performs its job without raising "
            "— degrade to `None`/the caller's default on any internal failure, "
            "never crash the host."
        )
    if idea.constraints.mvp_only:
        criteria.append("Scope stays within the MVP boundary noted below — no gold-plating.")
    if idea.dependencies.requires_network_egress:
        criteria.append(
            "Every outbound host is declared in the manifest's `egress_hosts` "
            "— no undeclared network egress."
        )
    return criteria


def generate_idea_doc(idea: PluginIdea, classification: Classification) -> str:
    c = classification
    lines = [
        f"# Plugin Idea: {idea.plugin_name}",
        "",
        "> Generated by the Plugin-Builder (ADR-0253). This is a starting "
        "point, not a promise of good design — review and edit before you "
        "build.",
        "",
        "## Problem",
        "",
        idea.problem.problem,
        "",
        "## Target Audience",
        "",
        idea.problem.target_audience,
        "",
        "## Existing Solutions / Workarounds",
        "",
        idea.problem.existing_solutions or "_None noted._",
        "",
        "## Scope",
        "",
        f"- Time/scope constraint: {idea.problem.time_scope}",
        f"- {'MVP only' if idea.constraints.mvp_only else 'Full scope from day one'}",
        f"- Notes: {idea.constraints.scope_notes or '_none_'}",
        "",
        "## Classification",
        "",
        f"- **Kind:** {c.kind.value}",
        f"- **Tier:** {c.tier.value} (ADR-0156)",
        f"- **Confidence:** {c.confidence:.0%}",
    ]
    if c.plugin_type:
        lines.append(f"- **Plugin type:** `{c.plugin_type}` (`corvin_plugins.protocol.KNOWN_PLUGIN_TYPES`)")
    if c.extension_point:
        lines.append(f"- **Extension point:** `{c.extension_point}`")
    lines += [f"- Rationale: {c.rationale}", ""]
    if c.risk_flags:
        lines.append("## Risks surfaced early")
        lines.append("")
        for flag in c.risk_flags:
            lines.append(f"- ⚠ {flag}")
        lines.append("")
    lines += ["## Success Criteria", ""]
    for item in _success_criteria(idea, c):
        lines.append(f"- {item}")
    lines.append("")
    return "\n".join(lines)


__all__ = ["generate_idea_doc"]
