"""Build Plan generator (ADR-0253 Phase 4 artifact #4).

Phases mirror this repo's own `loop-driven-engineering` discipline (K_MAX = 5,
cheap-to-expensive test pyramid) rather than inventing a separate planning
vocabulary — a plugin author working inside this codebase already knows that
shape.
"""
from __future__ import annotations

from ..models import Classification, PluginIdea, PluginKind

_KIND_IMPLEMENT_GATE = {
    PluginKind.MCP_SERVER: "`tools/list` and `tools/call` respond correctly over stdio JSON-RPC for at least one real tool.",
    PluginKind.SKILL: "The Markdown reads clearly to someone who has never seen the interview answers.",
    PluginKind.HOOK: "The hook returns `None` on every path it hasn't implemented yet, and the correct type on the ones it has.",
    PluginKind.PROVIDER: "`corvin plugin check <path>` passes with zero errors.",
    PluginKind.INTEGRATION: "The external call path has a real success case AND a real failure case tested.",
    PluginKind.CUSTOM: "N/A — this phase cannot start until the classification is resolved.",
}


def generate_build_plan_doc(idea: PluginIdea, classification: Classification) -> str:
    c = classification
    mvp = idea.constraints.mvp_only
    lines = [
        f"# Build Plan: {idea.plugin_name}",
        "",
        "> Generated by the Plugin-Builder (ADR-0253). Phases mirror this "
        "repo's loop-driven-engineering discipline — budget five iterations "
        "per phase before escalating, not before shipping.",
        "",
        "## Phase 1 — Scaffold + Manifest",
        "",
        "- [ ] Review the generated scaffold; rename the class to something "
        "real.",
        "- [ ] Fill in `plugin.yaml` (or the Tier A/C equivalent) — confirm "
        "`pii_risk`, `requires_consent`, `network_egress` match what this "
        "plugin actually does, not just the least-privileged default.",
        "- [ ] **Gate:** the scaffold imports/parses cleanly, unmodified.",
        "",
        "## Phase 2 — Implement the Capability",
        "",
        f"- [ ] Implement the {c.kind.value} logic described in the "
        "Architecture Concept.",
        f"- [ ] **Gate:** {_KIND_IMPLEMENT_GATE[c.kind]}",
        "",
        "## Phase 3 — Tests",
        "",
        "- [ ] Unit tests for the plugin's own logic.",
    ]
    if c.kind == PluginKind.PROVIDER:
        lines.append("- [ ] `corvin plugin check <path>` in CI, not just locally.")
        lines.append(
            "- [ ] Integration test against a throwaway registry confirming "
            "the class satisfies `CorvinPlugin` (`isinstance` check, same "
            "pattern as `core/plugins/tests/test_template_conformance.py`)."
        )
    if c.kind == PluginKind.HOOK:
        lines.append(
            "- [ ] Integration test with `plugin_extension_points` explicitly "
            "on AND explicitly off — both must behave as documented."
        )
    lines.append("- [ ] **Gate:** every test above is green, not skipped.")
    lines += [
        "",
        "## Phase 4 — Validate + Document",
        "",
        "- [ ] Update this plugin's own README with real install instructions.",
        "- [ ] If anything in Architecture/ADR turned out wrong during "
        "implementation, fix those documents in the same change — stale "
        "design docs are worse than none.",
        "- [ ] **Gate:** a reader with no prior context could install and "
        "use this plugin from the README alone.",
        "",
        "## Phase 5 — Install + Review",
        "",
        "- [ ] Manual install per the README (`spec.plugins.installed` in "
        "`tenant.corvin.yaml`, or a `corvin.plugins` entry point with "
        "`auto_discover_entry_points: true`).",
    ]
    if c.tier.value in ("B", "C"):
        lines.append(
            "- [ ] Confirm this doesn't exceed your license's active "
            "executable-layer count (Tier B/C, ADR-0156) — free tier allows "
            "one."
        )
    if not mvp:
        lines.append(
            "- [ ] Full scope was requested — confirm nothing from the MVP "
            "boundary got silently dropped along the way."
        )
    lines += [
        "- [ ] For anything beyond `origin: community` (vetted/builtin, "
        "compliance/core boot layer): that is a maintainer decision, not a "
        "flag this plan can check off alone.",
        "",
    ]
    return "\n".join(lines)


__all__ = ["generate_build_plan_doc"]
