"""ADR-0184 (Autostart) drift guard: two independent Windows restart-loop
implementations exist by necessity —

- `operator/bridges/shared/corvin-supervisor.ps1` (dev-checkout path, used by
  `bridge.ps1 install-autostart`)
- the heredoc-generated supervisor inside `install.ps1`'s
  `Install-CorvinAutostart` (the pip/uv-tool standalone path, which must stay
  self-contained since it runs via `irm | iex` before any repo checkout
  necessarily exists on disk — see the comment above that function)

They can't be merged into one file without adding a network dependency to the
installer, so instead this test pins them to the SAME bounded-restart shape
(ADR-0184 Stufe-1: 5 restarts per 300s window, then stop) so a future edit to
one doesn't silently leave the other with an unbounded crash loop — the exact
drift class `tests/test_uninstall_windows_autostart.py` already documents for
the autostart *registration* side of these same two files.
"""
from __future__ import annotations

import re
from pathlib import Path

_REPO = Path(__file__).resolve().parent.parent
_SUPERVISOR = _REPO / "operator" / "bridges" / "shared" / "corvin-supervisor.ps1"
_INSTALL_PS1 = _REPO / "install.ps1"
_INSTALL_SH = _REPO / "install.sh"
_BRIDGE_PS1 = _REPO / "operator" / "bridges" / "bridge.ps1"
_BRIDGE_MANAGER = _REPO / "operator" / "bridges" / "bridge_manager.py"


def _generated_supervisor_block() -> str:
    """Extract the heredoc body install.ps1 writes out as its own
    corvin-supervisor.ps1, with the backtick-escapes install.ps1 needs (to
    keep the text literal inside ITS OWN here-string) stripped back out —
    this normalizes it to look like what actually lands on disk at install
    time, so it's directly comparable to the checked-in dev-checkout file."""
    src = _INSTALL_PS1.read_text(encoding="utf-8")
    start = src.index('@"\n# Auto-generated by install.ps1')
    end = src.index('"@ | Set-Content', start)
    block = src[start:end]
    return block.replace("`$", "$")


class TestBoundedRestartParity:
    def test_both_files_use_the_same_restart_cap_and_window(self) -> None:
        supervisor_src = _SUPERVISOR.read_text(encoding="utf-8")
        generated_src = _generated_supervisor_block()

        for label, src in (("corvin-supervisor.ps1", supervisor_src),
                            ("install.ps1 generated block", generated_src)):
            assert re.search(r"MaxRestarts\s*=\s*5\b", src), (
                f"{label}: expected MaxRestarts=5 (ADR-0184 Stufe-1 cap)"
            )
            assert re.search(r"RestartWindowSec\s*=\s*300\b", src), (
                f"{label}: expected RestartWindowSec=300 (ADR-0184 Stufe-1 window)"
            )

    def test_both_files_have_a_rolling_window_filter_before_the_cap_check(self) -> None:
        """Guards against someone re-adding a naive `while($true){...; sleep 5}`
        with no cap at all — the Where-Object rolling-window filter must run
        before the Count-vs-MaxRestarts comparison in both files."""
        for label, src in (
            ("corvin-supervisor.ps1", _SUPERVISOR.read_text(encoding="utf-8")),
            ("install.ps1 generated block", _generated_supervisor_block()),
        ):
            where_idx = src.find("Where-Object")
            cap_idx = src.find("Count -ge")
            assert where_idx != -1, f"{label}: missing rolling-window filter"
            assert cap_idx != -1, f"{label}: missing restart-cap check"
            assert where_idx < cap_idx, (
                f"{label}: rolling-window filter must run BEFORE the cap check"
            )

    def test_both_files_stop_instead_of_looping_forever_once_capped(self) -> None:
        for label, src in (
            ("corvin-supervisor.ps1", _SUPERVISOR.read_text(encoding="utf-8")),
            ("install.ps1 generated block", _generated_supervisor_block()),
        ):
            cap_idx = src.find("Count -ge")
            assert cap_idx != -1, f"{label}: missing restart-cap check"
            # `break` must appear shortly after the cap check fires — i.e. the
            # loop actually stops instead of merely logging and continuing.
            window = src[cap_idx:cap_idx + 400]
            assert "break" in window, (
                f"{label}: restart cap is checked but the loop doesn't `break`"
            )

    def test_both_files_fail_safe_on_an_ambiguous_port_check(self) -> None:
        """2026-08-02 adversarial finding: the port-busy standby check used to
        treat ANY exception lacking `.Exception.Response` as "port is free"
        — which also covers a connect TIMEOUT (firewall/proxy silently
        dropping the connection, or a process alive-but-slow-to-answer), not
        just a genuine refused connection. That risked launching a SECOND
        competing instance against an existing one that just hadn't
        responded within 3s yet. Fixed to require the specific, well-defined
        `ConnectFailure` status before concluding the port is free; anything
        else (including Timeout) is treated as busy. Pinned in both files —
        parity is load-bearing, same as the restart-cap shape above."""
        for label, src in (
            ("corvin-supervisor.ps1", _SUPERVISOR.read_text(encoding="utf-8")),
            ("install.ps1 generated block", _generated_supervisor_block()),
        ):
            assert "WebExceptionStatus" in src and "ConnectFailure" in src, (
                f"{label}: port-busy check must distinguish ConnectFailure "
                f"(genuinely free) from other failures (Timeout etc., "
                f"treated as busy) instead of a bare `if ($_.Exception.Response)`"
            )
            # The ConnectFailure branch must be the only one that clears
            # portBusy to $false — everything else in the catch block must
            # default to busy ($true), never a bare fallthrough that leaves
            # the pre-try $portBusy = $false unexamined.
            catch_idx = src.find("catch {")
            connectfailure_idx = src.find("ConnectFailure", catch_idx)
            assert catch_idx != -1 and connectfailure_idx != -1, (
                f"{label}: could not locate the port-busy catch block"
            )
            window = src[catch_idx:connectfailure_idx + 200]
            assert "portBusy = $false" in window and "portBusy = $true" in window, (
                f"{label}: expected an explicit else-branch defaulting to "
                f"busy, not just the ConnectFailure allow-list"
            )


class TestScheduledTaskSettingsParity:
    """The Scheduled-Task registration itself (Trigger/Settings/RunLevel) is
    a second, independent copy in bridge.ps1 (dev-checkout) vs install.ps1
    (standalone) — same drift risk as the supervisor loop above. Pin the
    settings that matter for "survives crash/reboot" so they can't quietly
    diverge (e.g. one script losing -RestartCount or switching RunLevel)."""

    def test_both_use_atlogon_trigger(self) -> None:
        for label, path in (("bridge.ps1", _BRIDGE_PS1), ("install.ps1", _INSTALL_PS1)):
            src = path.read_text(encoding="utf-8")
            assert "New-ScheduledTaskTrigger -AtLogOn" in src, (
                f"{label}: expected the Stufe-1 -AtLogOn trigger"
            )

    def test_both_use_the_same_settings_set_flags(self) -> None:
        expected = [
            "-Hidden",
            "-AllowStartIfOnBatteries",
            "-DontStopIfGoingOnBatteries",
            "-ExecutionTimeLimit ([TimeSpan]::Zero)",
            "-RestartCount 999",
            "-RestartInterval (New-TimeSpan -Minutes 1)",
            "-MultipleInstances IgnoreNew",
        ]
        for label, path in (("bridge.ps1", _BRIDGE_PS1), ("install.ps1", _INSTALL_PS1)):
            src = path.read_text(encoding="utf-8")
            for flag in expected:
                assert flag in src, f"{label}: missing/changed ScheduledTaskSettingsSet flag {flag!r}"

    def test_both_register_with_limited_run_level(self) -> None:
        """RunLevel Limited (not Highest) is the whole point of Stufe 1 — no
        elevation. A silent switch to -RunLevel Highest here would turn the
        default, no-consent path into an elevated one (ADR-0184 Decision 3)."""
        for label, path in (("bridge.ps1", _BRIDGE_PS1), ("install.ps1", _INSTALL_PS1)):
            src = path.read_text(encoding="utf-8")
            assert "-RunLevel Limited" in src, f"{label}: expected -RunLevel Limited"
            assert "-RunLevel Highest" not in src, (
                f"{label}: found -RunLevel Highest — Stufe 1 must never require elevation"
            )


class TestNoClosableWindow:
    """Regression for a real bug: install.ps1's Install-CorvinAutostart falls
    back to a bare `Start-Process corvinos-serve` if Scheduled-Task
    registration throws for any reason. That fallback used to pass
    `-WindowStyle Minimized` — which still creates a taskbar entry the user
    can click and close, silently killing the "background" process exactly
    the way a visible console window would. Every process this installer
    starts must be `-WindowStyle Hidden` (no window at all) or run via a
    Scheduled Task with `-Hidden` — never Minimized/Normal/Maximized, which
    all leave something on screen for a user to close."""

    _NOT_ALLOWED = re.compile(r"-WindowStyle\s+(Minimized|Normal|Maximized)\b")

    def test_no_closable_windowstyle_anywhere(self) -> None:
        for label, path in (("install.ps1", _INSTALL_PS1), ("bridge.ps1", _BRIDGE_PS1)):
            src = path.read_text(encoding="utf-8")
            match = self._NOT_ALLOWED.search(src)
            assert not match, (
                f"{label}: found {match.group(0) if match else ''} — must be "
                "-WindowStyle Hidden, not a style that leaves a closable window"
            )

    def test_install_ps1_fallback_start_uses_hidden(self) -> None:
        src = _INSTALL_PS1.read_text(encoding="utf-8")
        fallback_idx = src.index("Could not set up any autostart")
        window = src[fallback_idx:fallback_idx + 1200]
        assert "corvinos-serve" in window, "fallback Start-Process call not found where expected"
        assert "-WindowStyle Hidden" in window, (
            "install.ps1's no-autostart fallback must launch corvinos-serve with "
            "-WindowStyle Hidden, not a visible/minimized window"
        )


class TestScheduledTaskArgumentQuoting:
    """2026-08-02 adversarial finding: bridge.ps1's Install-AutostartTask
    built a flat Scheduled-Task action-argument string with $Supervisor
    correctly quoted but $TargetArg/$BridgeArg interpolated bare — the exact
    class of quoting mistake corvin-supervisor.ps1's own header docstring
    says this whole design (native array args, not a flat re-parsed string)
    exists to avoid. $BridgeArg in particular is operator-supplied (the
    -Bridge CLI argument); a name containing a space or embedded quote would
    break the CLI parsing powershell.exe does on the action string."""

    def test_target_and_bridge_args_are_quoted_in_the_action_string(self) -> None:
        src = _BRIDGE_PS1.read_text(encoding="utf-8")
        idx = src.index("$ArgString")
        window = src[idx:idx + 400]
        assert '-Target `"$TargetArg`"' in window or '-Target "$TargetArg"' in window, (
            "bridge.ps1: -Target value must be quoted in the Scheduled Task "
            "action string, matching how $Supervisor is already quoted"
        )
        assert '-Bridge `"$BridgeArg`"' in window or '-Bridge "$BridgeArg"' in window, (
            "bridge.ps1: -Bridge value must be quoted in the Scheduled Task "
            "action string — an operator-supplied bridge name with a space "
            "or quote would otherwise break the action's own CLI parsing"
        )


class TestBridgeUpDaemonIsDetached:
    """2026-08-02 real bug, reported live: `bridge.ps1 up`'s node-daemon
    launch used `& node $BridgeScript` — the call operator (`&`) runs node as
    a DIRECT CHILD of the invoking PowerShell session, sharing its console.
    Closing that terminal window kills the whole process tree, daemon
    included. `Start-Process` (without -NoNewWindow) gives the child its OWN
    independent console instead — -WindowStyle Hidden just keeps that
    separate console invisible; the child's lifecycle is no longer tied to
    the caller's window at all. This is the same pattern the "console" case
    in the same file already used (Start-Process ... -WindowStyle Hidden)."""

    def test_up_case_does_not_attach_the_daemon_to_the_caller_console(self) -> None:
        src = _BRIDGE_PS1.read_text(encoding="utf-8")
        up_idx = src.index('"up" {')
        doctor_idx = src.index('"doctor" {')
        window = src[up_idx:doctor_idx]
        assert "& node $BridgeScript" not in window, (
            "bridge.ps1: the 'up' case must not launch node via the call "
            "operator (&) — that attaches the daemon to the caller's own "
            "console, so closing that terminal kills the bridge"
        )

    def test_up_case_uses_start_process_hidden_for_the_daemon(self) -> None:
        src = _BRIDGE_PS1.read_text(encoding="utf-8")
        up_idx = src.index('"up" {')
        doctor_idx = src.index('"doctor" {')
        window = src[up_idx:doctor_idx]
        assert "Start-Process" in window and '-FilePath "node"' in window, (
            "bridge.ps1: the 'up' case must launch node via Start-Process, "
            "not the call operator"
        )
        assert "-WindowStyle Hidden" in window, (
            "bridge.ps1: the 'up' case's node launch must be -WindowStyle "
            "Hidden — a Minimized/Normal/Maximized window is still closable"
        )
        assert "-NoNewWindow" not in window, (
            "bridge.ps1: the 'up' case must NOT pass -NoNewWindow — that "
            "would put the daemon back on the caller's own console, the "
            "exact thing -WindowStyle Hidden's separate console avoids"
        )

    def test_up_case_captures_daemon_output_to_a_log_file(self) -> None:
        """A detached process's stdout/stderr is invisible in the terminal —
        must not be silently discarded (the WhatsApp pairing QR code and any
        daemon startup error both go through this output)."""
        src = _BRIDGE_PS1.read_text(encoding="utf-8")
        up_idx = src.index('"up" {')
        doctor_idx = src.index('"doctor" {')
        window = src[up_idx:doctor_idx]
        assert "-RedirectStandardOutput" in window, (
            "bridge.ps1: the 'up' case must capture the detached daemon's "
            "stdout to a log file"
        )


class TestSupervisorBridgeRecursionHidden:
    """corvin-supervisor.ps1's "bridge" target recurses into `bridge.ps1 up`
    via a nested powershell.exe — that nested process's OWN -WindowStyle
    switch should be Hidden too (belt-and-suspenders alongside the outer
    Start-Process's -NoNewWindow), matching every other Scheduled-Task
    action string in this codebase (install.ps1, bridge.ps1's own
    Install-AutostartTask)."""

    def test_bridge_target_arglist_passes_windowstyle_hidden(self) -> None:
        src = _SUPERVISOR.read_text(encoding="utf-8")
        idx = src.index('$FilePath = "powershell.exe"')
        window = src[idx:idx + 300]
        assert '"-WindowStyle", "Hidden"' in window or "-WindowStyle Hidden" in window, (
            "corvin-supervisor.ps1: the bridge-target recursion into "
            "bridge.ps1 must pass -WindowStyle Hidden to the nested "
            "powershell.exe, matching every other Scheduled-Task action "
            "string in this codebase"
        )


class TestInstallBannerReflectsRealState:
    """2026-08-02 real bug, reported live: a fresh Windows install left the
    console not running, yet install.ps1's final banner unconditionally
    printed "CorvinOS is ready!" -- regardless of whether the server ever
    answered healthz, whether autostart registration succeeded, or whether
    the direct-start fallback (see TestNoClosableWindow above) even ran.
    The one real Write-Warn from an earlier step was buried in scrollback
    under a big green false-positive success banner -- exactly what a user
    reads/screenshots when reporting "it doesn't work". The banner must be
    gated on $ServerReady / $ConsoleLaunchAttempted, not printed
    unconditionally, and the no-launch path must give an explicit recovery
    command rather than silently claiming success."""

    def test_success_banner_is_conditional_on_server_ready(self) -> None:
        src = _INSTALL_PS1.read_text(encoding="utf-8")
        idx = src.index('# ── done / cheat sheet')
        window = src[idx:idx + 800]
        assert re.search(r"if\s*\(\$ServerReady\)", window), (
            "install.ps1's final 'CorvinOS is ready!' banner must be gated on "
            "$ServerReady, not printed unconditionally"
        )

    def test_no_launch_path_gives_an_actionable_recovery_command(self) -> None:
        src = _INSTALL_PS1.read_text(encoding="utf-8")
        idx = src.index('# ── done / cheat sheet')
        window = src[idx:idx + 3200]
        assert "could NOT be started" in window, (
            "install.ps1 must have an explicit failure banner for the case "
            "where nothing actually launched -- not fall through to a "
            "success message"
        )
        assert "corvinos-serve" in window[window.index("could NOT be started"):], (
            "the failure banner must tell the user the exact recovery "
            "command (corvinos-serve) rather than leaving them with no "
            "next step"
        )

    def test_fallback_start_failure_is_not_silently_swallowed(self) -> None:
        # Regression for the specific empty `catch {}` this session found:
        # `try { Start-Process -FilePath "corvinos-serve" ... } catch {}` --
        # any failure (including "not found") vanished with zero output,
        # and $ConsoleLaunchAttempted still let the banner claim success.
        src = _INSTALL_PS1.read_text(encoding="utf-8")
        assert 'ArgumentList "--no-browser" -WindowStyle Hidden -ErrorAction Stop } catch {}' not in src, (
            "the single-shot fallback start must not use an empty catch "
            "block -- a failure there must be surfaced via Write-Warn, not "
            "discarded"
        )
        idx = src.index("Could not set up any autostart")
        window = src[idx:idx + 1200]
        assert "ConsoleLaunchAttempted" in window, (
            "the fallback path must track whether the launch actually "
            "succeeded, not assume success"
        )


class TestLanFirewallRule:
    """2026-08-02 real bug, reported via a screenshot: A2A pairing between a
    Windows and a Linux instance on the same LAN got stuck at "Imported
    (URL pending)" / UNREACHABLE. Windows' default inbound-block policy
    silently drops the peer's reachability probe with no visible cause.
    install.ps1 now adds a best-effort inbound firewall rule for the
    console/A2A port, mirroring the Install-CorvinAutostart idiom: never
    fatal, idempotent (removes any stale rule by name first), no admin/
    elevation gate (this installer never checks for elevation anywhere
    else either -- New-NetFirewallRule just throws on a non-admin account
    and the caller's catch reports it as a warning like every other
    privileged step)."""

    def test_firewall_function_defined_and_idempotent(self) -> None:
        src = _INSTALL_PS1.read_text(encoding="utf-8")
        assert "function Install-CorvinFirewallRule" in src
        idx = src.index("function Install-CorvinFirewallRule")
        body = src[idx:idx + 1400]
        assert "Remove-NetFirewallRule" in body, (
            "must remove any stale rule by name first (idempotent re-run, "
            "matching Install-CorvinAutostart's Unregister-then-Register)"
        )
        assert "New-NetFirewallRule" in body
        assert "-Direction Inbound" in body
        assert "-Action Allow" in body

    def test_firewall_rule_is_called_with_the_real_console_port(self) -> None:
        src = _INSTALL_PS1.read_text(encoding="utf-8")
        assert "$ConsolePort = 8765" in src, (
            "the console's actual default port (8765, per serve_entry.py / "
            "cli.py) must be used, not a hardcoded/wrong port like 8000"
        )
        call_idx = src.index("Install-CorvinFirewallRule -Port $ConsolePort")
        window = src[max(0, call_idx - 400):call_idx]
        assert "try {" in window, "firewall rule creation must be wrapped in try/catch"

    def test_firewall_failure_is_reported_not_swallowed(self) -> None:
        src = _INSTALL_PS1.read_text(encoding="utf-8")
        call_idx = src.index("Install-CorvinFirewallRule -Port $ConsolePort")
        window = src[call_idx:call_idx + 500]
        assert "catch {" in window
        assert "Write-Warn" in window, (
            "a failure to add the firewall rule must be surfaced to the "
            "user with a manual recovery command, not silently discarded"
        )


class TestLinuxUfwRule:
    """Linux counterpart of TestLanFirewallRule: install.sh must never
    invoke sudo outside the explicit --always-on opt-in (an unconditional
    sudo prompt mid one-liner install would be a real regression), so the
    ufw step is gated on ufw already being active and never shells out to
    sudo itself."""

    def test_ufw_step_present_and_scoped_to_linux(self) -> None:
        src = _INSTALL_SH.read_text(encoding="utf-8")
        assert "command -v ufw" in src
        idx = src.index("command -v ufw")
        window = src[max(0, idx - 300):idx + 700]
        assert '"Linux"' in window
        assert "ufw allow 8765/tcp" in window
        assert "Status: active" in window, (
            "must only touch ufw if it is already active -- never enable a "
            "firewall the operator hasn't turned on themselves"
        )

    def test_ufw_step_never_invokes_sudo(self) -> None:
        # "sudo" MAY appear once, but only inside the printed recovery
        # message (_bold 'sudo ufw allow ...') -- it must never be an
        # actually-executed command in this block.
        src = _INSTALL_SH.read_text(encoding="utf-8")
        idx = src.index("command -v ufw")
        window = src[idx:idx + 900]
        executed_sudo = re.findall(r"(?<!')\bsudo\s+ufw\b", window)
        assert not executed_sudo, (
            "install.sh only elevates via sudo when --always-on is "
            "explicitly passed -- the ufw step must degrade to a printed "
            "manual command instead of prompting for a password unasked"
        )
        assert "_bold 'sudo ufw allow" in window, (
            "expected the manual-recovery command to be printed via _bold"
        )


class TestBridgeUpBlocksUnderSupervision:
    """2026-08-02 real bug, found while investigating a live report of an
    unreliable Windows bridge: corvin-supervisor.ps1's bridge target
    launches `bridge.ps1 up` via `Start-Process ... -Wait` -- but `up`
    always returned within ~1s of firing off the DETACHED node.js daemon,
    whether or not that daemon was still alive. The supervisor's -Wait was
    therefore only ever waiting on the launcher script, not the real
    daemon, so its while($true) loop launched a BRAND NEW node.js daemon
    every ~5s forever regardless of the previous one's health -- silent
    duplicate daemons fighting over the same Discord/WhatsApp session
    (session-file locking, duplicate replies, rate-limit bans). Fixed:
    `up` now blocks on the daemon's own Process object when
    CORVIN_SUPERVISED=1 (the same signal corvin-supervisor.ps1 already
    sets before every launch), so the supervisor's -Wait finally reflects
    the daemon's real lifetime. An interactive, unsupervised
    `.\bridge.ps1 up` must keep returning immediately."""

    def test_up_case_waits_for_the_daemon_when_supervised(self) -> None:
        src = _BRIDGE_PS1.read_text(encoding="utf-8")
        start_idx = src.index('"up" {')
        # Bounded to this case's own block -- the next top-level case
        # ("doctor") starts the next section.
        end_idx = src.index('"doctor" {', start_idx)
        block = src[start_idx:end_idx]
        assert "$Proc = Start-Process" in block, (
            "expected the daemon Start-Process call (-PassThru) in the up case"
        )
        proc_idx = block.index("$Proc = Start-Process")
        after = block[proc_idx:]
        assert re.search(r"CORVIN_SUPERVISED", after), (
            "the up case must check the supervised signal after launching "
            "the daemon"
        )
        assert re.search(r"\$Proc\.WaitForExit\(\)", after), (
            "under supervision, up must block on the daemon's OWN Process "
            "object (not the launcher script) so the supervisor's -Wait "
            "reflects the daemon's real lifetime instead of restarting a "
            "fresh duplicate daemon on a fixed interval"
        )

    def test_wait_for_exit_is_conditional_not_unconditional(self) -> None:
        # A manual, interactive `.\bridge.ps1 up` (CORVIN_SUPERVISED unset)
        # must still return immediately -- regression guard against
        # accidentally making WaitForExit unconditional, which would make
        # a manual run hang until the daemon exits.
        src = _BRIDGE_PS1.read_text(encoding="utf-8")
        idx = src.index("$Proc.WaitForExit()")
        window = src[max(0, idx - 200):idx]
        assert re.search(r"if\s*\(\$env:CORVIN_SUPERVISED", window), (
            "WaitForExit() must be gated behind an if ($env:CORVIN_SUPERVISED "
            "...) check, not called unconditionally"
        )


class TestWindowsAutostartRegistrationHasNoVisibleWindow:
    """2026-08-02 real bug, reported live: an extra terminal window flashed
    up on Windows that the user had to click away/close. Root cause:
    bridge_manager.py's ensure_windows_autostart() (added in the 0.10.92
    fix for missing bridge autostart supervision) spawned powershell.exe via
    a bare subprocess.run with no CREATE_NO_WINDOW/DETACHED_PROCESS flag --
    reintroducing, for THIS specific call, exactly the class of bug 0.10.91
    had just fixed for the node daemon's own launch. Windows allocates a
    brand-new, VISIBLE console window for any console app spawned without
    that flag from a parent that itself has no attached console (the web
    console backend, started hidden).

    2026-08-03: bridge_manager.py's own subprocess.run() call sites (this
    one included) were consolidated behind a single `_run()` wrapper that
    applies CREATE_NO_WINDOW by default for every plain subprocess.run() in
    the file (see operator/bridges/tests/test_bridge_manager_no_console_
    window.py, which pins _run() itself and drift-guards that no bare
    subprocess.run() call bypasses it). This test now only pins that
    ensure_windows_autostart routes through that wrapper rather than
    reintroducing its own bare subprocess.run()."""

    def test_ensure_windows_autostart_spawns_with_no_visible_window(self) -> None:
        src = _BRIDGE_MANAGER.read_text(encoding="utf-8")
        idx = src.index("def ensure_windows_autostart")
        next_def_idx = src.index("\ndef ", idx + 1)
        body = src[idx:next_def_idx]
        assert "subprocess.run(" not in body, (
            "ensure_windows_autostart must call the module's _run() wrapper, "
            "not a bare subprocess.run() -- a bare call here would bypass "
            "the centralized CREATE_NO_WINDOW fix and reintroduce the "
            "visible-console-window bug for this specific spawn"
        )
        assert "_run(" in body, (
            "ensure_windows_autostart must spawn powershell.exe via the "
            "module's _run() wrapper so CREATE_NO_WINDOW is applied -- "
            "otherwise Windows opens a new, visible console window when "
            "spawned from a console-less parent (the hidden web console "
            "backend), exactly matching the live report of an extra "
            "terminal window the user has to dismiss"
        )


class TestScheduledTaskLaunchesViaHiddenVbsWrapper:
    """2026-08-03 real bug, reported live AGAIN after 0.10.103 (which only
    fixed bridge_manager.py's own Python-side subprocess spawns): a console
    window still flashed at logon. Root cause this time: the Scheduled Task
    Action itself executes `powershell.exe -WindowStyle Hidden ...` directly
    -- and powershell.exe's own -WindowStyle switch is a well-known, widely
    reported Windows/Task-Scheduler limitation (conhost/Windows Terminal
    shows the console window BEFORE powershell.exe can hide itself), not
    something fixable by passing the switch differently. No prior fix round
    touched this because it's the Task Scheduler Action's own Execute
    target, not a spawn made from already-running Python or PowerShell code.

    Fix: both bridge.ps1's Install-AutostartTask and install.ps1's
    Install-CorvinAutostart now generate a WScript.Shell .vbs wrapper and
    point the Scheduled Task Action at `wscript.exe` (a GUI-subsystem
    executable with no console of its own) instead of `powershell.exe`
    directly. WScript.Shell.Run(cmd, 0, False) suppresses the real
    powershell.exe child's window AT CREATION, not after -- the standard,
    documented fix for this exact class of bug."""

    def test_bridge_ps1_action_executes_wscript_not_powershell(self) -> None:
        src = _BRIDGE_PS1.read_text(encoding="utf-8")
        idx = src.index("function Install-AutostartTask")
        end_idx = src.index("Install-AutostartTask -TaskName", idx)
        body = src[idx:end_idx]
        assert 'New-ScheduledTaskAction -Execute "wscript.exe"' in body, (
            "bridge.ps1: the Scheduled Task Action must execute wscript.exe "
            "(running a generated .vbs wrapper), not powershell.exe directly "
            "-- powershell.exe's own -WindowStyle Hidden does not reliably "
            "suppress the console window when launched by Task Scheduler"
        )
        assert 'New-ScheduledTaskAction -Execute "powershell.exe"' not in body, (
            "bridge.ps1: the Scheduled Task Action must not execute "
            "powershell.exe directly anymore"
        )

    def test_install_ps1_action_executes_wscript_not_powershell(self) -> None:
        src = _INSTALL_PS1.read_text(encoding="utf-8")
        idx = src.index("function Install-CorvinAutostart")
        end_idx = src.index("function Install-CorvinFirewallRule", idx)
        body = src[idx:end_idx]
        assert 'New-ScheduledTaskAction -Execute "wscript.exe"' in body, (
            "install.ps1: the Scheduled Task Action must execute wscript.exe "
            "(running a generated .vbs wrapper), not powershell.exe directly"
        )
        assert 'New-ScheduledTaskAction -Execute "powershell.exe"' not in body, (
            "install.ps1: the Scheduled Task Action must not execute "
            "powershell.exe directly anymore"
        )

    def test_both_files_generate_a_vbs_wrapper_using_wscript_shell_run_hidden(self) -> None:
        for label, path in (("bridge.ps1", _BRIDGE_PS1), ("install.ps1", _INSTALL_PS1)):
            src = path.read_text(encoding="utf-8")
            assert 'CreateObject(""WScript.Shell"").Run' in src, (
                f"{label}: expected a generated .vbs body using "
                f"WScript.Shell.Run to launch powershell.exe hidden"
            )
            # The third Run() argument (window style) must be 0 (hidden at
            # creation) -- 1/Normal or any nonzero-but-visible style would
            # reintroduce a visible window.
            run_idx = src.index('CreateObject(""WScript.Shell"").Run')
            window = src[run_idx:run_idx + 300]
            assert re.search(r",\s*0,\s*False", window), (
                f"{label}: WScript.Shell.Run must be called with windowStyle=0 "
                f"(hidden) and waitOnReturn=False"
            )

    def test_both_files_launch_wscript_with_batch_flag_and_quoted_path(self) -> None:
        for label, path in (("bridge.ps1", _BRIDGE_PS1), ("install.ps1", _INSTALL_PS1)):
            src = path.read_text(encoding="utf-8")
            assert '-Argument "//B `"$VbsPath`""' in src, (
                f"{label}: the Scheduled Task Action argument must invoke "
                f"wscript.exe with //B (batch mode, suppresses error dialogs) "
                f"against the quoted .vbs path"
            )

    def test_install_ps1_fallback_shortcut_and_immediate_start_use_wscript_too(self) -> None:
        """The Startup-folder-shortcut fallback (denied Scheduled-Task
        permission) must get the same real hiding as the primary path -- a
        .lnk's own WindowStyle property has no true 'hidden' state, only
        Minimized, which still leaves a closable taskbar entry."""
        src = _INSTALL_PS1.read_text(encoding="utf-8")
        idx = src.index("falling back to a Startup-folder shortcut")
        window = src[idx:idx + 1200]
        assert '-TargetPath "wscript.exe"' in window, (
            "install.ps1: the Startup-folder shortcut fallback must target "
            "wscript.exe (running the same .vbs wrapper), not powershell.exe"
        )
        assert '-FilePath "wscript.exe"' in window, (
            "install.ps1: the immediate one-shot start in this fallback "
            "must also launch via wscript.exe, not powershell.exe directly"
        )


if __name__ == "__main__":
    import sys

    t = TestBoundedRestartParity()
    t.test_both_files_use_the_same_restart_cap_and_window()
    t.test_both_files_have_a_rolling_window_filter_before_the_cap_check()
    t.test_both_files_stop_instead_of_looping_forever_once_capped()
    t2 = TestScheduledTaskSettingsParity()
    t2.test_both_use_atlogon_trigger()
    t2.test_both_use_the_same_settings_set_flags()
    t2.test_both_register_with_limited_run_level()
    t3 = TestNoClosableWindow()
    t3.test_no_closable_windowstyle_anywhere()
    t3.test_install_ps1_fallback_start_uses_hidden()
    t4 = TestBridgeUpDaemonIsDetached()
    t4.test_up_case_does_not_attach_the_daemon_to_the_caller_console()
    t4.test_up_case_uses_start_process_hidden_for_the_daemon()
    t4.test_up_case_captures_daemon_output_to_a_log_file()
    t5 = TestSupervisorBridgeRecursionHidden()
    t5.test_bridge_target_arglist_passes_windowstyle_hidden()
    t6 = TestInstallBannerReflectsRealState()
    t6.test_success_banner_is_conditional_on_server_ready()
    t6.test_no_launch_path_gives_an_actionable_recovery_command()
    t6.test_fallback_start_failure_is_not_silently_swallowed()
    t7 = TestLanFirewallRule()
    t7.test_firewall_function_defined_and_idempotent()
    t7.test_firewall_rule_is_called_with_the_real_console_port()
    t7.test_firewall_failure_is_reported_not_swallowed()
    t8 = TestLinuxUfwRule()
    t8.test_ufw_step_present_and_scoped_to_linux()
    t8.test_ufw_step_never_invokes_sudo()
    t9 = TestBridgeUpBlocksUnderSupervision()
    t9.test_up_case_waits_for_the_daemon_when_supervised()
    t9.test_wait_for_exit_is_conditional_not_unconditional()
    t10 = TestWindowsAutostartRegistrationHasNoVisibleWindow()
    t10.test_ensure_windows_autostart_spawns_with_no_visible_window()
    t11 = TestScheduledTaskLaunchesViaHiddenVbsWrapper()
    t11.test_bridge_ps1_action_executes_wscript_not_powershell()
    t11.test_install_ps1_action_executes_wscript_not_powershell()
    t11.test_both_files_generate_a_vbs_wrapper_using_wscript_shell_run_hidden()
    t11.test_both_files_launch_wscript_with_batch_flag_and_quoted_path()
    t11.test_install_ps1_fallback_shortcut_and_immediate_start_use_wscript_too()
    print("all tests passed")
    sys.exit(0)
