"""Video Spec Schema (Pydantic) — ADR-0955 Phase 1

Immutable schema for LLM-generated video specifications.
All specs must validate against this schema before execution.
"""

from typing import List, Optional, Dict, Any
from dataclasses import dataclass, field
from datetime import datetime
from pydantic import BaseModel, Field, validator
import re


class VideoMetadata(BaseModel):
    """Video metadata (resolution, FPS, duration, language)"""
    duration_seconds: int = Field(..., ge=1, le=600)  # 1–600 seconds
    fps: int = Field(default=30, ge=24, le=60)  # 24–60 FPS
    resolution: tuple[int, int] = Field(default=(1920, 1080))  # width x height
    language: str = Field(default="de", pattern="^[a-z]{2}$")  # ISO 639-1
    narrator_voice: str = Field(default="nova")  # OpenAI voice preset


class VisualElement(BaseModel):
    """Visual element (text, box, shape, etc.)"""
    type: str = Field(..., pattern="^(text|box|shape|image|animation)$")
    text: Optional[str] = None
    x: int = Field(default=0, ge=0)
    y: int = Field(default=0, ge=0)
    size: Optional[int] = Field(default=24, ge=8, le=200)
    color: Optional[str] = Field(default="#FFFFFF", pattern="^#[0-9A-F]{6}$")
    width: Optional[int] = Field(default=None, ge=1)
    height: Optional[int] = Field(default=None, ge=1)
    metadata: Dict[str, Any] = Field(default_factory=dict)

    @validator("color")
    def valid_hex_color(cls, v):
        if v and not re.match(r"^#[0-9A-F]{6}$", v):
            raise ValueError(f"Invalid hex color: {v}")
        return v


class SVGDiagram(BaseModel):
    """SVG diagram specification"""
    nodes: List[Dict[str, Any]] = Field(default_factory=list)
    edges: List[Dict[str, Any]] = Field(default_factory=list)
    layout: str = Field(default="hierarchical", pattern="^(hierarchical|circular|force|custom)$")
    width: int = Field(default=1920)
    height: int = Field(default=1080)


class BlenderSpec(BaseModel):
    """Blender 3D rendering specification"""
    scene: str = Field(...)  # Path to .blend file
    camera: str = Field(default="Camera")  # Camera name in scene
    animation: Optional[str] = None  # Animation name or "none"
    start_frame: int = Field(default=0)
    end_frame: int = Field(default=300)
    resolution_scale: int = Field(default=100, ge=50, le=100)


class Scene(BaseModel):
    """Single video scene"""
    id: str = Field(..., pattern="^[a-z_0-9]+$")
    type: str = Field(..., pattern="^(slide|svg_diagram|blender_render|screencast)$")
    duration_seconds: int = Field(..., ge=1, le=300)
    elements: List[VisualElement] = Field(default_factory=list)
    narration: str = Field(...)
    narration_duration_ms: int = Field(..., ge=100, le=600000)
    svg_spec: Optional[SVGDiagram] = None
    blender_spec: Optional[BlenderSpec] = None
    metadata: Dict[str, Any] = Field(default_factory=dict)

    @validator("narration")
    def narration_not_empty(cls, v):
        if not v or len(v.strip()) == 0:
            raise ValueError("Narration cannot be empty")
        return v

    @validator("narration_duration_ms")
    def duration_range_check(cls, v, values):
        if "duration_seconds" in values:
            max_ms = values["duration_seconds"] * 1000
            if v > max_ms + 5000:  # Allow 5s buffer
                raise ValueError(f"Narration duration {v}ms > scene duration {max_ms}ms + buffer")
        return v


class GenerationMetadata(BaseModel):
    """LLM generation metadata (immutable)"""
    generated_at: datetime = Field(default_factory=datetime.utcnow)
    llm_model: str = Field(default="claude-opus-5")
    llm_temperature: float = Field(default=0.3, ge=0.0, le=1.0)
    prompt_hash: str = Field(...)  # SHA256 of prompt
    request_hash: str = Field(...)  # SHA256 of request


class VideoSpec(BaseModel):
    """Complete video specification (ADR-0955)

    Immutable, tool-neutral video specification generated by LLM.
    Every spec must:
    1. Pass JSON schema validation
    2. Pass semantic validation (fail-closed)
    3. Be auditable (generation_metadata + request_hash)
    4. Be cached (by request_hash)
    """
    spec_version: str = Field(default="1.0")
    generation_metadata: GenerationMetadata = Field(...)
    video_metadata: VideoMetadata = Field(...)
    scenes: List[Scene] = Field(..., min_items=1, max_items=20)

    @validator("scenes")
    def total_duration_check(cls, v, values):
        total = sum(s.duration_seconds for s in v)
        if "video_metadata" in values:
            target = values["video_metadata"].duration_seconds
            if abs(total - target) > 5:  # ±5 seconds tolerance
                raise ValueError(f"Total scene duration {total}s ≠ target {target}s")
        return v

    @validator("scenes")
    def no_duplicate_ids(cls, v):
        ids = [s.id for s in v]
        if len(ids) != len(set(ids)):
            raise ValueError("Duplicate scene IDs")
        return v

    class Config:
        frozen = True  # Immutable after creation


# Validation utility functions

def estimate_tts_duration_ms(text: str, language: str = "de", words_per_minute: int = 140) -> int:
    """Estimate OpenAI TTS duration in milliseconds

    German (de): ~140 words/min = 2.4 sec/word
    English (en): ~160 words/min = 2.1 sec/word
    """
    word_count = len(text.split())
    if language == "en":
        words_per_minute = 160

    duration_seconds = (word_count / words_per_minute) * 60
    return int(duration_seconds * 1000)


def validate_narration_timing(scene: Scene) -> tuple[bool, str]:
    """Validate narration duration vs scene duration

    Tolerance: ±2 seconds (2000 ms)
    """
    target_ms = scene.duration_seconds * 1000
    actual_ms = scene.narration_duration_ms
    tolerance_ms = 2000

    if abs(actual_ms - target_ms) > tolerance_ms:
        return False, f"Narration {actual_ms}ms ≠ scene {target_ms}ms (tolerance ±{tolerance_ms}ms)"

    return True, "OK"


if __name__ == "__main__":
    # Example: Create a valid spec
    spec = VideoSpec(
        generation_metadata=GenerationMetadata(
            llm_model="claude-opus-5",
            prompt_hash="abc123",
            request_hash="def456",
        ),
        video_metadata=VideoMetadata(
            duration_seconds=60,
            fps=30,
            resolution=(1920, 1080),
            language="de",
        ),
        scenes=[
            Scene(
                id="intro",
                type="slide",
                duration_seconds=10,
                elements=[
                    VisualElement(type="text", text="ACS RUNNER", size=72, color="#4287F5"),
                ],
                narration="ACS Runner. Autonomous Context Selection.",
                narration_duration_ms=estimate_tts_duration_ms("ACS Runner. Autonomous Context Selection."),
            ),
        ],
    )
    print(f"✅ Valid spec created: {spec.spec_version}")
