"""corvin_plugins — unified plugin system for Corvin (ADR-0030)."""
from __future__ import annotations

from .extension_points import (
    KNOWN_EXTENSION_POINTS,
    CrossTenantHookRefused,
    ExtensionPointDenied,
    ExtensionPointError,
    ExtensionPointSpec,
    ImmutableExtensionPoint,
    UnknownExtensionPoint,
    invoke,
    register_hook,
    unregister_all,
)
from .manifest import (
    BootLayer,
    BreakingChange,
    CircularDependencyError,
    DependencyConflictError,
    DependencyResolver,
    PIIRisk,
    PluginDependency,
    PluginError,
    PluginManifest,
    PluginOrigin,
    PluginRecord,
    SettingsValidator,
    UnknownPluginType,
    UpdatePolicy,
    ValidationError,
    plan_settings_migration,
)
from .protocol import (
    KNOWN_PLUGIN_TYPES,
    CorvinPlugin,
    HealthStatus,
    PluginAlreadyRegistered,
    PluginContext,
    PluginDisableRefused,
    PluginNotFound,
    PluginReplacementRefused,
)
from .registry import (
    PluginRegistry,
    boot_layer_of,
    can_disable,
    disable,
    discover,
    get,
    get_registry,
    health_check_all,
    plugins_by_boot_layer,
    register,
    replace,
    unregister,
)

__all__ = [
    # protocol — the lifecycle contract (ADR-0030)
    "CorvinPlugin",
    "HealthStatus",
    "KNOWN_PLUGIN_TYPES",
    "PluginAlreadyRegistered",
    "PluginContext",
    "PluginDisableRefused",
    "PluginNotFound",
    "PluginReplacementRefused",
    # registry — runtime registration
    "PluginRegistry",
    "register",
    "unregister",
    "disable",
    "can_disable",
    "boot_layer_of",
    "plugins_by_boot_layer",
    "replace",
    "get",
    "health_check_all",
    "discover",
    "get_registry",
    # extension_points — named hooks into boot_layer=core defaults (ADR-0237)
    "KNOWN_EXTENSION_POINTS",
    "CrossTenantHookRefused",
    "ExtensionPointDenied",
    "ExtensionPointError",
    "ExtensionPointSpec",
    "ImmutableExtensionPoint",
    "UnknownExtensionPoint",
    "invoke",
    "register_hook",
    "unregister_all",
    # manifest — registry records, dependency order, settings (ADR-0233)
    "BreakingChange",
    "CircularDependencyError",
    "DependencyConflictError",
    "DependencyResolver",
    "PIIRisk",
    "PluginDependency",
    "PluginError",
    "BootLayer",
    "PluginManifest",
    "PluginOrigin",
    "PluginRecord",
    "SettingsValidator",
    "UnknownPluginType",
    "UpdatePolicy",
    "ValidationError",
    "plan_settings_migration",
]
