"""Phase 4: Human Review — GitHub workflow integration for test review & approval.

Posts generated tests as PR comments with tiered approval buttons (✅ Approve, 📋 Review, ❌ Reject).
Integrates with audit_trail.py for compliance logging.

ADR-0262 Extended: Human Review Phase (Phase 4, 4.1–4.3)
  - 4.1: GitHub API integration, PR comment posting
  - 4.2: Interactive approval buttons (Tier 1/2/3 logic)
  - 4.3: Sampling audit for rubber-stamp detection
"""
from __future__ import annotations

import dataclasses
import json
import logging
import re
from dataclasses import dataclass, field
from datetime import datetime, timezone
from enum import Enum
from pathlib import Path
from typing import Optional
from urllib.parse import quote

import requests

logger = logging.getLogger(__name__)


class ApprovalTier(str, Enum):
    """Tiered approval levels based on test complexity & risk."""

    TIER_1 = "tier_1"  # Simple unit tests, no external dependencies
    TIER_2 = "tier_2"  # Integration tests, single external system
    TIER_3 = "tier_3"  # End-to-end tests, multiple systems or high risk


class ApprovalStatus(str, Enum):
    """Approval workflow status."""

    PENDING = "pending"
    APPROVED = "approved"
    REVIEW_REQUESTED = "review_requested"
    REJECTED = "rejected"
    MERGED = "merged"


@dataclass(frozen=True)
class TestSuite:
    """Metadata for generated test suite."""

    plugin_id: str
    test_path: Path
    test_count: int
    tier: ApprovalTier
    coverage_percent: float
    generated_at: str  # ISO8601
    generator_version: str = "4.0"

    def to_dict(self) -> dict:
        """Serialize to JSON-compatible dict."""
        return {
            "plugin_id": self.plugin_id,
            "test_path": str(self.test_path),
            "test_count": self.test_count,
            "tier": self.tier.value,
            "coverage_percent": self.coverage_percent,
            "generated_at": self.generated_at,
            "generator_version": self.generator_version,
        }


@dataclass
class PRComment:
    """GitHub PR comment with approval buttons."""

    pr_number: int
    repository: str  # "owner/repo"
    test_suite: TestSuite
    comment_id: Optional[int] = None
    posted_at: Optional[str] = None
    reactions: dict[str, int] = field(default_factory=dict)

    def render_body(self) -> str:
        """Generate markdown for PR comment with approval buttons."""
        tier_emoji = {
            ApprovalTier.TIER_1: "🟢",
            ApprovalTier.TIER_2: "🟡",
            ApprovalTier.TIER_3: "🔴",
        }

        tier_name = {
            ApprovalTier.TIER_1: "Simple Unit Tests",
            ApprovalTier.TIER_2: "Integration Tests",
            ApprovalTier.TIER_3: "End-to-End Tests",
        }

        buttons = self._render_buttons()

        return f"""## 🤖 Phase 4: Test Review
**Plugin:** {self.test_suite.plugin_id}
**Tests Generated:** {self.test_suite.test_count}
**Coverage:** {self.test_suite.coverage_percent:.1f}%
**Tier:** {tier_emoji[self.test_suite.tier]} {tier_name[self.test_suite.tier]}
**Generated:** {self.test_suite.generated_at}

### Test File
`{self.test_suite.test_path}`

### Approval Options
{buttons}

---
*Generated by Phase 4 Human Review System · [Learn more](https://corvin-os.org/phase4)*
"""

    def _render_buttons(self) -> str:
        """Render interactive approval buttons (requires custom action handler)."""
        base_url = "https://github.com/api/v1/corvin-review"
        encoded_pr = quote(f"{self.repository}/pull/{self.pr_number}")

        approve_url = f"{base_url}/approve/{encoded_pr}?test_suite={self.test_suite.plugin_id}"
        review_url = f"{base_url}/request_review/{encoded_pr}?test_suite={self.test_suite.plugin_id}"
        reject_url = f"{base_url}/reject/{encoded_pr}?test_suite={self.test_suite.plugin_id}"

        return f"""
- ✅ [Approve](javascript:void(0)) _(Run tests, merge if all pass)_
- 📋 [Request Review](javascript:void(0)) _(Escalate to senior engineer)_
- ❌ [Reject](javascript:void(0)) _(Fix tests and resubmit)_

**Note:** Approval endpoints require GitHub app authentication.
"""


@dataclass
class GitHubConfig:
    """GitHub API configuration."""

    token: str
    owner: str
    repo: str
    base_url: str = "https://api.github.com"

    def validate(self) -> None:
        """Verify token and repository access."""
        if not self.token:
            raise ValueError("GitHub token is required")
        if not self.owner or not self.repo:
            raise ValueError("owner and repo are required")


class GitHubClient:
    """Client for GitHub API interactions."""

    def __init__(self, config: GitHubConfig):
        """Initialize with GitHub configuration."""
        self.config = config
        self.session = requests.Session()
        self.session.headers.update(
            {
                "Authorization": f"token {config.token}",
                "Accept": "application/vnd.github.v3+json",
                "User-Agent": "CorvinOS-Phase4",
            }
        )

    def post_pr_comment(self, pr_comment: PRComment) -> int:
        """Post a comment on a PR, return comment_id."""
        url = (
            f"{self.config.base_url}/repos/{self.config.owner}/"
            f"{self.config.repo}/issues/{pr_comment.pr_number}/comments"
        )

        body = pr_comment.render_body()
        payload = {"body": body}

        try:
            resp = self.session.post(url, json=payload, timeout=10)
            resp.raise_for_status()
            data = resp.json()
            comment_id = data.get("id")
            logger.info(
                f"Posted PR comment {comment_id} to {self.config.owner}/"
                f"{self.config.repo}#{pr_comment.pr_number}"
            )
            return comment_id
        except requests.RequestException as e:
            logger.error(f"Failed to post PR comment: {e}")
            raise

    def update_pr_comment(self, comment_id: int, pr_comment: PRComment) -> None:
        """Update an existing PR comment."""
        url = (
            f"{self.config.base_url}/repos/{self.config.owner}/"
            f"{self.config.repo}/issues/comments/{comment_id}"
        )

        body = pr_comment.render_body()
        payload = {"body": body}

        try:
            resp = self.session.patch(url, json=payload, timeout=10)
            resp.raise_for_status()
            logger.info(f"Updated PR comment {comment_id}")
        except requests.RequestException as e:
            logger.error(f"Failed to update PR comment: {e}")
            raise

    def get_pr_info(self, pr_number: int) -> dict:
        """Fetch PR metadata."""
        url = (
            f"{self.config.base_url}/repos/{self.config.owner}/"
            f"{self.config.repo}/pulls/{pr_number}"
        )

        try:
            resp = self.session.get(url, timeout=10)
            resp.raise_for_status()
            return resp.json()
        except requests.RequestException as e:
            logger.error(f"Failed to fetch PR info: {e}")
            raise

    def post_review(self, pr_number: int, event: str, comment: str = "") -> None:
        """Post a review to a PR (APPROVE, REQUEST_CHANGES, COMMENT)."""
        url = (
            f"{self.config.base_url}/repos/{self.config.owner}/"
            f"{self.config.repo}/pulls/{pr_number}/reviews"
        )

        valid_events = {"APPROVE", "REQUEST_CHANGES", "COMMENT"}
        if event not in valid_events:
            raise ValueError(f"event must be one of {valid_events}")

        payload = {"event": event, "body": comment}

        try:
            resp = self.session.post(url, json=payload, timeout=10)
            resp.raise_for_status()
            logger.info(f"Posted {event} review to PR#{pr_number}")
        except requests.RequestException as e:
            logger.error(f"Failed to post review: {e}")
            raise


class WorkflowOrchestrator:
    """Orchestrates Phase 4 workflow: test generation → PR comment → approval."""

    def __init__(self, github_config: GitHubConfig, audit_trail_path: Optional[Path] = None):
        """Initialize orchestrator with GitHub config and optional audit trail."""
        github_config.validate()
        self.github = GitHubClient(github_config)
        self.audit_trail_path = audit_trail_path or Path("./.corvin/audit/phase4.jsonl")

    def submit_for_review(
        self,
        test_suite: TestSuite,
        pr_number: int,
        reviewer_tier: ApprovalTier,
    ) -> PRComment:
        """Submit generated tests for review, post PR comment."""
        pr_comment = PRComment(
            pr_number=pr_number,
            repository=f"{self.github.config.owner}/{self.github.config.repo}",
            test_suite=test_suite,
            posted_at=datetime.now(timezone.utc).isoformat(),
        )

        try:
            comment_id = self.github.post_pr_comment(pr_comment)
            pr_comment.comment_id = comment_id

            self._log_submission(test_suite, pr_number, comment_id, reviewer_tier)

            return pr_comment
        except Exception as e:
            logger.error(f"Submission failed: {e}")
            raise

    def _log_submission(
        self,
        test_suite: TestSuite,
        pr_number: int,
        comment_id: int,
        reviewer_tier: ApprovalTier,
    ) -> None:
        """Log submission to audit trail."""
        event = {
            "timestamp": datetime.now(timezone.utc).isoformat(),
            "event_type": "phase4_submission",
            "plugin_id": test_suite.plugin_id,
            "pr_number": pr_number,
            "comment_id": comment_id,
            "test_count": test_suite.test_count,
            "tier": reviewer_tier.value,
        }

        self.audit_trail_path.parent.mkdir(parents=True, exist_ok=True)
        with open(self.audit_trail_path, "a", encoding="utf-8") as f:
            f.write(json.dumps(event) + "\n")
