/**
 * Forged tab — plugins generated by Forge → Plugin Forge (ADR-2217 D5).
 *
 * Honest about what they are: generated, NOT installed, unsigned, and they
 * install as community code. They never appear under Browse, which lists only
 * the real marketplace index. A generated panel is previewed in an iframe
 * sandboxed to `allow-scripts` alone — never `allow-same-origin` — because it
 * is unreviewed community HTML.
 */
import { useRef, useState } from "react";
import { Link } from "react-router-dom";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { AlertCircle, Loader2, Package } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { useAuth } from "@/lib/auth";
import { Findings } from "@/components/forge/ForgeCreatorPanel";
import {
  FORGED_PANEL_SANDBOX,
  deleteForgedPlugin,
  previewDocument,
  getForgedPlugin,
  listForgedPlugins,
  type ForgedPluginSummary,
} from "@/lib/api/forge-creator";

const KEY = ["forge-creator", "plugins"] as const;

export function ForgedTab() {
  const [open, setOpen] = useState<string | null>(null);
  const list = useQuery({ queryKey: [...KEY], queryFn: ({ signal }) => listForgedPlugins(signal) });

  if (list.isLoading) return <Loader2 className="h-5 w-5 animate-spin text-muted-foreground" />;
  if (list.isError) {
    return (
      <p role="alert" className="flex items-center gap-2 text-sm text-destructive">
        <AlertCircle className="h-4 w-4" /> Forged plugins could not be listed.
      </p>
    );
  }
  const plugins = list.data?.plugins ?? [];
  return (
    <div className="space-y-4" data-testid="forged-tab">
      <p className="text-sm text-muted-foreground">
        Plugins generated by Plugin Forge. They are staged for your review and are{" "}
        <strong>not installed</strong>: they are unsigned and would install as community code.
      </p>
      {plugins.length === 0 ? (
        <p className="text-sm text-muted-foreground" data-testid="forged-empty">
          Nothing forged yet. <Link to="/app/forge?tab=plugin-forge" className="text-accent underline">Generate a plugin</Link>.
        </p>
      ) : (
        plugins.map((p) => (
          <ForgedRow key={p.dirname} p={p} open={open === p.dirname}
                     onToggle={() => setOpen(open === p.dirname ? null : p.dirname)} />
        ))
      )}
    </div>
  );
}

function ForgedRow({ p, open, onToggle }: { p: ForgedPluginSummary; open: boolean; onToggle: () => void }) {
  const { session } = useAuth();
  const qc = useQueryClient();
  const [confirm, setConfirm] = useState(false);
  const remove = useMutation({
    mutationFn: () => deleteForgedPlugin(p.dirname, session?.csrf_token ?? ""),
    onSuccess: () => qc.invalidateQueries({ queryKey: [...KEY] }),
  });
  return (
    <Card data-testid="forged-row">
      <CardContent className="space-y-3 p-4">
        <div className="flex flex-wrap items-center gap-2">
          <Package className="h-4 w-4 text-accent" />
          <span className="font-medium">{p.display_name}</span>
          <code className="font-mono text-xs text-muted-foreground">{p.plugin_id}</code>
          <Badge variant="secondary">Not installed</Badge>
          <Badge variant="outline">Unsigned · community</Badge>
          <Badge variant="outline">{p.kind}</Badge>
          <Badge variant="outline">Tier {p.tier}</Badge>
          {p.has_panel && <Badge variant="outline">Has panel</Badge>}
          {p.quality !== null && <Badge variant="outline">Review {Math.round(p.quality * 100)}%</Badge>}
        </div>
        {p.risk_flags.length > 0 && (
          <ul className="text-xs text-muted-foreground">
            {p.risk_flags.map((f) => <li key={f}>Risk: {f}</li>)}
          </ul>
        )}
        <div className="flex gap-2">
          <Button size="sm" variant="outline" onClick={onToggle} data-testid="forged-toggle">
            {open ? "Hide details" : "Details"}
          </Button>
          {confirm ? (
            <>
              <Button size="sm" variant="destructive" disabled={remove.isPending || !session}
                      onClick={() => remove.mutate()} data-testid="forged-delete-confirm">
                Delete files
              </Button>
              <Button size="sm" variant="ghost" onClick={() => setConfirm(false)}>Cancel</Button>
            </>
          ) : (
            <Button size="sm" variant="ghost" onClick={() => setConfirm(true)} data-testid="forged-delete">
              Delete
            </Button>
          )}
        </div>
        {remove.isError && <p role="alert" className="text-xs text-destructive">Not deleted: {(remove.error as Error).message}</p>}
        {open && <ForgedDetail dirname={p.dirname} />}
      </CardContent>
    </Card>
  );
}

/** Self-navigation inside a `sandbox="allow-scripts"` frame (no `allow-top-navigation`,
 *  no `allow-popups`) isn't blocked by the sandbox or the CSP — only a same-frame
 *  redirect is possible, but that's enough to beacon data out via the new URL. Any
 *  such re-navigation (location change, clicked link, meta refresh) fires a SECOND
 *  `load` event on this element, regardless of mechanism — so count loads and blank
 *  the frame the instant a second one fires, rather than trying to enumerate every
 *  in-frame navigation primitive (see FORGED_PANEL_LOCKDOWN in forge-creator.ts for
 *  the best-effort in-frame half of this defense). */
function SandboxedPanelPreview({ title, html }: { title: string; html: string }) {
  const loads = useRef(0);
  const [blocked, setBlocked] = useState(false);
  if (blocked) {
    return (
      <p role="alert" className="text-xs text-destructive" data-testid="forged-panel-blocked">
        Preview stopped: the panel tried to navigate away from its own content.
      </p>
    );
  }
  return (
    <iframe
      title={title}
      sandbox={FORGED_PANEL_SANDBOX}
      srcDoc={previewDocument(html)}
      onLoad={() => {
        loads.current += 1;
        if (loads.current > 1) setBlocked(true);
      }}
      className="h-64 w-full rounded-md border border-border/60 bg-white"
      data-testid="forged-panel-preview"
    />
  );
}

function ForgedDetail({ dirname }: { dirname: string }) {
  const detail = useQuery({ queryKey: [...KEY, dirname], queryFn: ({ signal }) => getForgedPlugin(dirname, signal) });
  const [file, setFile] = useState<string | null>(null);
  if (detail.isLoading) return <Loader2 className="h-4 w-4 animate-spin text-muted-foreground" />;
  if (!detail.data) return <p className="text-xs text-destructive">Details could not be loaded.</p>;
  const d = detail.data;
  const shown = d.files.find((f) => f.path === file);
  return (
    <div className="space-y-3 border-t border-border/60 pt-3 text-xs" data-testid="forged-detail">
      {d.request_chars !== null && (
        <p className="text-muted-foreground">
          Generated from a {d.request_chars}-character request (only its fingerprint is kept).
        </p>
      )}
      {d.egress_hosts.length > 0 && <p><span className="text-muted-foreground">Network hosts:</span> {d.egress_hosts.join(", ")}</p>}
      <Findings items={d.findings} skipped={d.review_skipped} />
      {d.warnings.map((w) => <p key={w} className="text-muted-foreground">Note: {w}</p>)}
      {d.panel_html && (
        <div className="space-y-1">
          <p className="text-muted-foreground">
            Panel preview (sandboxed, scripts only, no network — no access to this console). It becomes a
            live panel only once plugin panels can be mounted after installation.
          </p>
          <SandboxedPanelPreview title={`${d.display_name} panel preview`} html={d.panel_html} />
        </div>
      )}
      <div className="flex flex-wrap gap-1">
        {d.files.map((f) => (
          <Button key={f.path} size="sm" variant={file === f.path ? "secondary" : "outline"}
                  className="h-6 px-2 font-mono text-[11px]" onClick={() => setFile(f.path)}>
            {f.path}
          </Button>
        ))}
      </div>
      {shown && (
        shown.content !== undefined
          ? <pre className="max-h-96 overflow-auto rounded-md bg-muted p-2 font-mono text-[11px]">{shown.content}</pre>
          : <p className="text-muted-foreground">Binary or large file — not shown.</p>
      )}
      <p className="text-muted-foreground">
        To install: review the code, move the plugin into the Corvin-Marketplace contributor tree with a
        manifest, and install it from Browse. Generated code is never installed from here.
      </p>
    </div>
  );
}
