"""__DISPLAY_NAME__ — an extension-point hook plugin (Tier B, ADR-0237/0251).

Generated by the Plugin-Builder (ADR-0253) from the ``hook_plugin`` template.
Copy this file, rename the class, fill in the TODOs.

A Hook customises ONE named step of a bundled reference implementation without
replacing it — see ``corvin_plugins.extension_points``. It is registered
through ``corvin_plugins.registry`` like any other plugin (that is how it gets
a real ``on_load(ctx)`` call with a trustworthy ``ctx.tenant_id`` — see that
module's docstring on why identity matters for a hook), which means it still
needs a ``plugin_type`` from ``KNOWN_PLUGIN_TYPES``. This template defaults to
``router_backend`` — a real, consumed type (ADR-0245) — purely so the plugin
loads; the actual routing capability below is a harmless pass-through. Pick a
different consumed type if one fits your plugin better; it has no effect on
the hook itself.

**Read before you fill in the hook body — three rules that are enforced, not
suggestions:**

1. **Return ``None`` to abstain**, on EVERY point, including fail-closed ones.
   ``None`` is never treated as "deny" — a hook with no opinion about this
   particular call must not accidentally answer for it.
2. **Never raise.** A raising hook is caught by the bus; on a normal point the
   caller falls back to the default, on a fail-closed point the caller is
   denied. Either way your plugin does not crash its host — but an uncaught
   exception still means your hook contributed nothing useful. Wrap risky work
   in a try/except and return ``None`` on failure.
3. **Return exactly the declared type or ``None`` — nothing else.** A wrong
   type is treated exactly like a raise (ADR-0251 D3), not like an abstention.
   Check ``corvin_plugins.extension_points.spec(point).return_type`` if unsure.

The extension-point bus itself ships OFF (``plugin_extension_points`` feature
flag, default false) — until an operator turns it on, ``on_load`` still runs
and still registers this hook, but nothing calls it.
"""
from __future__ import annotations

from typing import Any

from corvin_plugins.extension_points import register_hook, unregister_all
from corvin_plugins.protocol import HealthStatus, PluginContext

#: One of corvin_plugins.extension_points.KNOWN_EXTENSION_POINTS. TODO: confirm
#: this is still the point you want — the classifier's best guess, not a promise.
EXTENSION_POINT = "__EXTENSION_POINT__"


class MyHookPlugin:
    """Replace with your actual class name."""

    plugin_id = "__PLUGIN_ID__"
    plugin_type = "router_backend"  # see module docstring — chosen for consumed=True
    version = "1.0.0"
    display_name = "__DISPLAY_NAME__"

    def __init__(self) -> None:
        self._tenant_id: str | None = None

    # ── CorvinPlugin lifecycle ──────────────────────────────────────────────

    def on_load(self, ctx: PluginContext) -> None:
        self._tenant_id = ctx.tenant_id
        if ctx.router_registry is not None:
            ctx.router_registry.set_active(self)
        register_hook(
            EXTENSION_POINT,
            self._hook,
            plugin_id=self.plugin_id,
            tenant_id=ctx.tenant_id,
        )

    def on_unload(self) -> None:
        unregister_all(self.plugin_id)

    def health_check(self) -> HealthStatus:
        return HealthStatus(ok=True, message="ok")

    # ── router_backend capability (harmless pass-through, see module docstring) ─

    def route(self, text: str, personas: Any, *, min_confidence: float = 0.5,
              tenant_id: str = "_default") -> None:
        return None  # this plugin exists for its hook, not for routing

    # ── The actual hook ──────────────────────────────────────────────────────

    def _hook(self, *args: Any, **kwargs: Any) -> Any:
        """TODO: implement. Must return None (abstain), the point's declared
        type, or raise nothing at all — see the module docstring's three rules.
        """
        try:
            raise NotImplementedError  # TODO
        except Exception:
            return None
