"""__DISPLAY_NAME__ — a standalone MCP server (Tier C, ADR-0156).

Generated by the Plugin-Builder (ADR-0253) from the ``mcp_server_plugin``
template. Copy this file, fill in the TODOs, and run it as its own subprocess:

    python -m __PLUGIN_ID___mcp.server

This is DELIBERATELY not a ``corvin_plugins.CorvinPlugin`` — an MCP server is a
Tier-C surface (ADR-0156): it runs OUT of process and is reached over stdio
JSON-RPC, not through the in-process plugin registry. Wiring it into
CorvinOS is an operator/config step (register the subprocess command with
the MCP client that will spawn it), not a ``corvin_plugins`` install.

Transport: line-delimited JSON-RPC 2.0 on stdin/stdout, the same shape every
in-tree MCP server uses (``core/orchestration/corvin_orchestration/mcp_server.py``
is the reference implementation this skeleton mirrors). Each request is one
JSON object per line on stdin; each response is one JSON object per line on
stdout. Never print anything else to stdout — that would corrupt the stream.
"""
from __future__ import annotations

import json
import sys
import traceback
from typing import Any, Callable

PROTOCOL_VERSION = "2024-11-05"
SERVER_NAME = "__PLUGIN_ID__"
SERVER_VERSION = "0.1.0"

PARSE_ERROR = -32700
INVALID_REQUEST = -32600
METHOD_NOT_FOUND = -32601
INVALID_PARAMS = -32602
INTERNAL_ERROR = -32603


# ── TODO: define your tool(s) here ──────────────────────────────────────────
#
# Each tool is a name, a JSON-Schema for its input, and a handler. Keep
# handlers small and defensive — a raising handler is caught below and turned
# into a JSON-RPC error, never a crashed server.

def _example_tool(args: dict[str, Any]) -> dict[str, Any]:
    """TODO: replace with your real tool. This one just echoes its input."""
    return {"echo": args}


TOOLS: dict[str, dict[str, Any]] = {
    "__PLUGIN_ID___example": {
        "description": "TODO: describe what this tool does",
        "inputSchema": {
            "type": "object",
            "properties": {"text": {"type": "string"}},
            "required": ["text"],
        },
        "handler": _example_tool,
    },
}


# ── JSON-RPC plumbing — TODOs above are the only edits most authors need ───

def _respond(id_: Any, *, result: Any = None, error: dict[str, Any] | None = None) -> None:
    msg: dict[str, Any] = {"jsonrpc": "2.0", "id": id_}
    if error is not None:
        msg["error"] = error
    else:
        msg["result"] = result
    sys.stdout.write(json.dumps(msg) + "\n")
    sys.stdout.flush()


def _handle_initialize(_params: dict[str, Any]) -> dict[str, Any]:
    return {
        "protocolVersion": PROTOCOL_VERSION,
        "serverInfo": {"name": SERVER_NAME, "version": SERVER_VERSION},
        "capabilities": {"tools": {}},
    }


def _handle_tools_list(_params: dict[str, Any]) -> dict[str, Any]:
    return {
        "tools": [
            {"name": name, "description": spec["description"],
             "inputSchema": spec["inputSchema"]}
            for name, spec in TOOLS.items()
        ]
    }


def _handle_tools_call(params: dict[str, Any]) -> dict[str, Any]:
    name = params.get("name")
    spec = TOOLS.get(name)  # type: ignore[arg-type]
    if spec is None:
        raise KeyError(f"unknown tool {name!r}")
    args = params.get("arguments") or {}
    result = spec["handler"](args)
    return {"content": [{"type": "text", "text": json.dumps(result)}]}


_METHODS: dict[str, Callable[[dict[str, Any]], dict[str, Any]]] = {
    "initialize": _handle_initialize,
    "tools/list": _handle_tools_list,
    "tools/call": _handle_tools_call,
}


def _dispatch(request: dict[str, Any]) -> None:
    id_ = request.get("id")
    method = request.get("method")
    handler = _METHODS.get(method)  # type: ignore[arg-type]
    if handler is None:
        _respond(id_, error={"code": METHOD_NOT_FOUND, "message": f"unknown method {method!r}"})
        return
    try:
        result = handler(request.get("params") or {})
    except Exception as exc:  # noqa: BLE001 — a broken tool must not kill the server
        _respond(id_, error={
            "code": INTERNAL_ERROR,
            "message": f"{type(exc).__name__}: {exc}",
            "data": traceback.format_exc(limit=5),
        })
        return
    _respond(id_, result=result)


def main() -> None:
    for line in sys.stdin:
        line = line.strip()
        if not line:
            continue
        try:
            request = json.loads(line)
        except json.JSONDecodeError:
            _respond(None, error={"code": PARSE_ERROR, "message": "invalid JSON"})
            continue
        _dispatch(request)


if __name__ == "__main__":
    main()
