"""__DISPLAY_NAME__ — a __PLUGIN_TYPE__ provider plugin (Tier B, ADR-0033/0233).

Generated by the Plugin-Builder (ADR-0253) from the ``provider_plugin_generic``
template — used when the classified ``plugin_type`` has no shipped, protocol-
tracked template under ``core/plugins/templates/`` (today: ``data_connector``,
``stt_provider``; see ``corvin_plugins.surface_map``). This is a Builder-owned
scaffold, not an official template: it targets the base ``CorvinPlugin``
protocol correctly, but the type-specific capability methods have no declared
Protocol class to check against yet, so read ``corvin_plugins.providers.
__PLUGIN_TYPE__`` for the registry API before filling in the TODOs below.

**Before you invest real work: check whether anything calls this type at all.**
Run ``corvin plugin types`` (or read ``corvin_plugins.surface_map.surface_for
("__PLUGIN_TYPE__")``) — several of the 11 known plugin types register
successfully and are never invoked (ADR-0245). The Plugin-Builder's own
classifier already surfaced this as a risk flag if it applies to your idea;
this comment is the same warning at the point where you are about to write
code.
"""
from __future__ import annotations

from typing import Any

from corvin_plugins.protocol import HealthStatus, PluginContext

#: The PluginContext field this plugin registers itself with in on_load().
#: TODO: confirm against corvin_plugins.protocol.PluginContext — this is the
#: classifier's best guess (surface_map.ctx_handle for __PLUGIN_TYPE__).
CTX_HANDLE = "__CTX_HANDLE__"


class MyProviderPlugin:
    """Replace with your actual class name."""

    plugin_id = "__PLUGIN_ID__"
    plugin_type = "__PLUGIN_TYPE__"
    version = "1.0.0"
    display_name = "__DISPLAY_NAME__"

    def __init__(self) -> None:
        self._config: dict[str, Any] = {}

    # ── CorvinPlugin lifecycle ──────────────────────────────────────────────

    def on_load(self, ctx: PluginContext) -> None:
        self._config = ctx.config
        handle = getattr(ctx, CTX_HANDLE, None)
        if handle is not None:
            handle.set_active(self)
        # else: this ctx field is not populated by the process that loaded us.
        # See surface_map.py's dead_reason for __PLUGIN_TYPE__ before assuming
        # that's a bug in your plugin.

    def on_unload(self) -> None:
        pass

    def health_check(self) -> HealthStatus:
        return HealthStatus(ok=True, message="ok")

    # ── TODO: implement the __PLUGIN_TYPE__ capability ──────────────────────
    #
    # There is no declared Protocol class for this type yet — read
    # corvin_plugins/providers/__PLUGIN_TYPE__.py for the exact method(s) its
    # registry expects a `get_active()` plugin to expose, and mirror the
    # "must not raise" discipline every other capability method in this
    # codebase follows (wrap risky work in try/except; degrade, don't crash
    # the caller).
