"""
Coverage Impact Measurement — Phase 3.A
========================================

Measures coverage before/after code changes:
- Takes baseline coverage snapshot
- Runs tests
- Compares coverage delta
- Reports impact by file + function

Helps identify:
- Untested new code (coverage < 80%)
- Dead code removal (coverage increases)
- Test quality regression (coverage drops)
"""

import json
import logging
import subprocess
from dataclasses import dataclass, asdict, field
from pathlib import Path
from typing import Dict, List, Optional, Tuple


logger = logging.getLogger(__name__)


@dataclass
class FileCoverage:
    """Coverage metrics for one file."""
    file_path: str
    lines_total: int
    lines_covered: int
    coverage_percent: float  # 0-100
    missing_lines: List[int] = field(default_factory=list)


@dataclass
class FunctionCoverage:
    """Coverage metrics for one function."""
    function_name: str
    file_path: str
    lines: int
    coverage_percent: float


@dataclass
class CoverageSnapshot:
    """Full coverage snapshot at a point in time."""
    timestamp: str
    total_lines: int
    covered_lines: int
    total_coverage_percent: float
    by_file: Dict[str, FileCoverage] = field(default_factory=dict)
    by_function: Dict[str, FunctionCoverage] = field(default_factory=dict)


@dataclass
class CoverageImpactReport:
    """Before/after coverage comparison."""
    baseline: CoverageSnapshot
    current: CoverageSnapshot
    delta_coverage_percent: float  # negative = regression, positive = improvement
    new_files: List[str] = field(default_factory=list)
    improved_files: List[str] = field(default_factory=list)
    regressed_files: List[str] = field(default_factory=list)
    untested_functions: List[FunctionCoverage] = field(default_factory=list)
    risk_level: str = "LOW"  # LOW, MEDIUM, HIGH


class CoverageImpactMeasurement:
    """
    Measures code coverage impact of changes.

    Usage:
        measure = CoverageImpactMeasurement(repo_root="/path/to/CorvinOS")
        baseline = measure.capture_coverage(label="baseline")
        # ... make changes ...
        current = measure.capture_coverage(label="current")
        report = measure.compare(baseline, current)
        if report.delta_coverage_percent < -5.0:
            print(f"⚠ Coverage regression: {report.delta_coverage_percent:.1f}%")
    """

    def __init__(self, repo_root: Path = None, min_coverage: float = 80.0):
        self.repo_root = Path(repo_root) if repo_root else Path.cwd()
        self.min_coverage = min_coverage
        self._snapshots: Dict[str, CoverageSnapshot] = {}

    def capture_coverage(
        self,
        label: str = "snapshot",
        test_dir: str = "tests",
        coverage_file: str = ".coverage"
    ) -> CoverageSnapshot:
        """
        Run pytest with coverage and capture results.

        Args:
            label: Label for this snapshot (e.g., "baseline", "current")
            test_dir: Directory containing tests
            coverage_file: Coverage data file (generated by pytest-cov)

        Returns:
            CoverageSnapshot with metrics
        """
        logger.info(f"[COVERAGE] Capturing coverage ({label})...")

        # Run pytest with coverage
        try:
            cmd = [
                "python", "-m", "pytest",
                test_dir,
                f"--cov=core",
                "--cov-report=json",
                f"--cov-report=term",
                "-q"
            ]
            proc = subprocess.run(
                cmd,
                cwd=self.repo_root,
                capture_output=True,
                text=True,
                timeout=120
            )
            logger.info(f"  Coverage command completed (exit {proc.returncode})")
            if proc.stderr:
                logger.debug(f"  Coverage stderr: {proc.stderr[:200]}")

        except subprocess.TimeoutExpired:
            logger.error("  Coverage capture timed out")
            raise
        except Exception as e:
            logger.error(f"  Failed to capture coverage: {e}")
            raise

        # Parse coverage.json
        snapshot = self._parse_coverage_json()
        self._snapshots[label] = snapshot
        logger.info(f"  ✓ Coverage: {snapshot.total_coverage_percent:.1f}% "
                   f"({snapshot.covered_lines}/{snapshot.total_lines} lines)")
        return snapshot

    def _parse_coverage_json(self) -> CoverageSnapshot:
        """Parse .coverage output (if available) or infer from test output."""
        coverage_json = self.repo_root / "coverage.json"
        by_file = {}
        by_function = {}
        total_lines = 0
        covered_lines = 0

        if coverage_json.exists():
            try:
                with open(coverage_json) as f:
                    data = json.load(f)

                # Parse per-file coverage
                for file_path, file_data in data.get("files", {}).items():
                    if "core/" not in file_path:
                        continue

                    summary = file_data.get("summary", {})
                    num_statements = summary.get("num_statements", 0)
                    covered_lines_file = summary.get("covered_lines", 0)

                    if num_statements > 0:
                        coverage_pct = (covered_lines_file / num_statements) * 100
                        by_file[file_path] = FileCoverage(
                            file_path=file_path,
                            lines_total=num_statements,
                            lines_covered=covered_lines_file,
                            coverage_percent=coverage_pct,
                            missing_lines=file_data.get("excluded_lines", [])
                        )
                        total_lines += num_statements
                        covered_lines += covered_lines_file

            except Exception as e:
                logger.warning(f"Failed to parse coverage.json: {e}")

        total_coverage = (covered_lines / total_lines * 100) if total_lines > 0 else 0.0

        return CoverageSnapshot(
            timestamp=str(Path.cwd()),  # Simplified; could use datetime
            total_lines=total_lines,
            covered_lines=covered_lines,
            total_coverage_percent=total_coverage,
            by_file=by_file,
            by_function=by_function
        )

    def compare(
        self,
        baseline: CoverageSnapshot,
        current: CoverageSnapshot
    ) -> CoverageImpactReport:
        """
        Compare two coverage snapshots and identify impact.

        Returns:
            CoverageImpactReport with delta and risk assessment
        """
        logger.info("[COVERAGE] Comparing baseline vs current...")

        delta = current.total_coverage_percent - baseline.total_coverage_percent
        logger.info(f"  Coverage delta: {delta:+.1f}% "
                   f"({baseline.total_coverage_percent:.1f}% → {current.total_coverage_percent:.1f}%)")

        # Find improved/regressed files
        improved = []
        regressed = []
        new_files = []

        for file_path, current_cov in current.by_file.items():
            baseline_cov = baseline.by_file.get(file_path)
            if not baseline_cov:
                new_files.append(file_path)
                if current_cov.coverage_percent < self.min_coverage:
                    logger.warning(f"  ⚠ New file {file_path}: {current_cov.coverage_percent:.0f}% "
                                  f"(below {self.min_coverage:.0f}% target)")
            else:
                delta_file = current_cov.coverage_percent - baseline_cov.coverage_percent
                if delta_file > 1.0:
                    improved.append(file_path)
                elif delta_file < -1.0:
                    regressed.append(file_path)
                    logger.warning(f"  ⚠ Regressed: {file_path} "
                                  f"({baseline_cov.coverage_percent:.0f}% → {current_cov.coverage_percent:.0f}%)")

        # Identify untested functions (if available in coverage data)
        untested = [
            f for f in current.by_function.values()
            if f.coverage_percent == 0.0
        ]

        # Risk assessment
        risk_level = "LOW"
        if delta < -5.0 or len(regressed) > 0:
            risk_level = "HIGH"
        elif delta < -2.0:
            risk_level = "MEDIUM"

        report = CoverageImpactReport(
            baseline=baseline,
            current=current,
            delta_coverage_percent=delta,
            new_files=new_files,
            improved_files=improved,
            regressed_files=regressed,
            untested_functions=untested,
            risk_level=risk_level
        )

        logger.info(f"  Risk level: {report.risk_level} "
                   f"(delta {delta:+.1f}%, {len(regressed)} regressed, {len(new_files)} new)")
        return report

    def to_json(self, report: CoverageImpactReport) -> str:
        """Export report as JSON."""
        data = asdict(report)
        data['baseline']['by_file'] = {k: asdict(v) for k, v in report.baseline.by_file.items()}
        data['current']['by_file'] = {k: asdict(v) for k, v in report.current.by_file.items()}
        return json.dumps(data, indent=2)

    def summary(self, report: CoverageImpactReport) -> str:
        """Generate a human-readable summary."""
        lines = [
            f"Coverage Impact Report:",
            f"  Baseline: {report.baseline.total_coverage_percent:.1f}%",
            f"  Current:  {report.current.total_coverage_percent:.1f}%",
            f"  Delta:    {report.delta_coverage_percent:+.1f}%",
            f"  Risk:     {report.risk_level}",
            f"",
            f"  New files:     {len(report.new_files)}",
            f"  Improved:      {len(report.improved_files)}",
            f"  Regressed:     {len(report.regressed_files)}",
            f"  Untested:      {len(report.untested_functions)}",
        ]

        if report.regressed_files:
            lines.append("\nRegressed files:")
            for f in report.regressed_files:
                lines.append(f"  - {f}")

        if report.untested_functions and len(report.untested_functions) <= 5:
            lines.append("\nUntested functions:")
            for fn in report.untested_functions:
                lines.append(f"  - {fn.function_name} ({fn.file_path})")

        return "\n".join(lines)
