"""Learning event schema for Skill optimization (ADR-0683, ADR-0314)."""

from dataclasses import dataclass, field
from datetime import datetime
from typing import Dict, Any, Optional, List
from enum import Enum
import json


class LearningEventType(str, Enum):
    """Immutable event types for skill learning loop."""
    SKILL_EXECUTED = "skill_executed"
    OUTCOME_FEEDBACK = "outcome_feedback"
    CONFIDENCE_SCORE = "confidence_score"
    PREFERENCE_FEEDBACK = "preference_feedback"
    METRIC_OBSERVED = "metric_observed"
    CONFIG_OPTIMIZED = "config_optimized"
    SKILL_DISABLED = "skill_disabled"
    OPTIMIZATION_PROPOSED = "optimization_proposed"


class FeedbackOutcome(str, Enum):
    """Outcome feedback labels."""
    CORRECT = "correct"
    INCORRECT = "incorrect"
    PARTIAL = "partial"
    UNKNOWN = "unknown"


@dataclass(frozen=True)
class LearningEvent:
    """Immutable learning event (audit-first, never modified)."""

    event_type: LearningEventType
    skill_id: str
    tenant_id: str
    timestamp: datetime

    # Core payload (immutable)
    input: Dict[str, Any] = field(default_factory=dict)
    output: Dict[str, Any] = field(default_factory=dict)

    # Metadata
    event_id: str = field(default="")  # UUID, generated by store
    chain_hash: str = field(default="")  # SHA256(prev_hash + this_event), set by store
    prev_hash: str = field(default="")  # Hash of previous event, for chain link
    lom: str = field(default="")  # Line of Moral Responsibility

    def to_dict(self) -> Dict[str, Any]:
        """Serialize to dict for audit trail."""
        return {
            "event_type": self.event_type.value,
            "skill_id": self.skill_id,
            "tenant_id": self.tenant_id,
            "timestamp": self.timestamp.isoformat(),
            "input": self.input,
            "output": self.output,
            "event_id": self.event_id,
            "chain_hash": self.chain_hash,
            "prev_hash": self.prev_hash,
            "lom": self.lom,
        }


@dataclass(frozen=True)
class SkillExecutedEvent(LearningEvent):
    """Skill execution event (k=1 baseline)."""

    event_type: LearningEventType = field(default=LearningEventType.SKILL_EXECUTED, init=False)
    latency_ms: float = field(default=0.0)
    error: Optional[str] = field(default=None)

    def to_dict(self) -> Dict[str, Any]:
        d = super().to_dict()
        d.update({
            "latency_ms": self.latency_ms,
            "error": self.error,
        })
        return d


@dataclass(frozen=True)
class OutcomeFeedbackEvent(LearningEvent):
    """User feedback on skill outcome (k=1 baseline)."""

    event_type: LearningEventType = field(default=LearningEventType.OUTCOME_FEEDBACK, init=False)
    outcome: FeedbackOutcome = field(default=FeedbackOutcome.UNKNOWN)
    reason: str = field(default="")  # User-provided reason (never stored in audit)

    def to_dict(self) -> Dict[str, Any]:
        d = super().to_dict()
        d.update({
            "outcome": self.outcome.value,
            "reason": ""  # GDPR: never log user reasons
        })
        return d


@dataclass(frozen=True)
class ConfidenceScoreEvent(LearningEvent):
    """Confidence score observation (k=1 baseline)."""

    event_type: LearningEventType = field(default=LearningEventType.CONFIDENCE_SCORE, init=False)
    confidence: float = field(default=0.5)  # 0.0-1.0
    basis: str = field(default="")  # How confidence was calculated

    def to_dict(self) -> Dict[str, Any]:
        d = super().to_dict()
        d.update({
            "confidence": self.confidence,
            "basis": self.basis,
        })
        return d


class LearningEventStore:
    """In-memory event collection for k=1 (serialized to disk via audit backend)."""

    def __init__(self, tenant_id: str):
        self.tenant_id = tenant_id
        self.events: List[LearningEvent] = []
        self._event_count: Dict[str, int] = {}

    def append_event(self, event: LearningEvent) -> LearningEvent:
        """Append immutable event to chain (audit-first)."""
        if event.tenant_id != self.tenant_id:
            raise ValueError(f"Tenant mismatch: {event.tenant_id} != {self.tenant_id}")

        # Set chain hash (in k=1, this is placeholder; k=2 will verify)
        prev_hash = self.events[-1].chain_hash if self.events else ""
        event_dict = event.to_dict()
        event_dict.update({
            "prev_hash": prev_hash,
            "chain_hash": self._compute_hash(prev_hash, event_dict),
        })

        # Recreate event with updated hashes
        if isinstance(event, SkillExecutedEvent):
            event = SkillExecutedEvent(
                event_type=event.event_type,
                skill_id=event.skill_id,
                tenant_id=event.tenant_id,
                timestamp=event.timestamp,
                input=event.input,
                output=event.output,
                latency_ms=event.latency_ms,
                error=event.error,
                chain_hash=event_dict["chain_hash"],
                prev_hash=event_dict["prev_hash"],
                lom=event.lom,
            )
        elif isinstance(event, OutcomeFeedbackEvent):
            event = OutcomeFeedbackEvent(
                event_type=event.event_type,
                skill_id=event.skill_id,
                tenant_id=event.tenant_id,
                timestamp=event.timestamp,
                input=event.input,
                output=event.output,
                outcome=event.outcome,
                reason=event.reason,
                chain_hash=event_dict["chain_hash"],
                prev_hash=event_dict["prev_hash"],
                lom=event.lom,
            )
        elif isinstance(event, ConfidenceScoreEvent):
            event = ConfidenceScoreEvent(
                event_type=event.event_type,
                skill_id=event.skill_id,
                tenant_id=event.tenant_id,
                timestamp=event.timestamp,
                input=event.input,
                output=event.output,
                confidence=event.confidence,
                basis=event.basis,
                chain_hash=event_dict["chain_hash"],
                prev_hash=event_dict["prev_hash"],
                lom=event.lom,
            )
        else:
            event = LearningEvent(
                event_type=event.event_type,
                skill_id=event.skill_id,
                tenant_id=event.tenant_id,
                timestamp=event.timestamp,
                input=event.input,
                output=event.output,
                chain_hash=event_dict["chain_hash"],
                prev_hash=event_dict["prev_hash"],
                lom=event.lom,
            )

        self.events.append(event)
        self._event_count[event.event_type.value] = self._event_count.get(event.event_type.value, 0) + 1
        return event

    def get_events(self, event_type: Optional[LearningEventType] = None) -> List[LearningEvent]:
        """Retrieve events by type (tenant-scoped, never cross-tenant)."""
        if event_type is None:
            return self.events
        return [e for e in self.events if e.event_type == event_type]

    def event_count(self, event_type: LearningEventType) -> int:
        """Count events of a specific type."""
        return self._event_count.get(event_type.value, 0)

    def to_jsonl(self) -> str:
        """Serialize to JSONL format for audit trail."""
        lines = [json.dumps(e.to_dict()) for e in self.events]
        return "\n".join(lines)

    @staticmethod
    def _compute_hash(prev_hash: str, event_dict: Dict[str, Any]) -> str:
        """Compute SHA256 hash (k=1 placeholder, no verification)."""
        import hashlib
        payload = json.dumps(event_dict, sort_keys=True)
        return hashlib.sha256((prev_hash + payload).encode()).hexdigest()
