"""Testing framework for generated plugins (ADR-0262 Phase 2 & 3).

Provides pytest fixtures, base test classes, and test runners for plugin
scaffolds generated by Plugin-Builder v2. Enables plugin developers to:
- Test lifecycle hooks (on_load, on_execute, on_unload)
- Test extension-point integration
- Test error handling and edge cases
- Validate audit trail events

Stream C (Phase 3): Real-LLM Testing Framework
- RealLLMHarness for Anthropic API integration
- HaikuClassifier for plugin type classification
- OpusCheckpointer for deep plugin analysis
- PluginTestContext with audit-chain support
- E2E testing with real LLM models

Each scaffold includes a conftest.py that imports from this module.
This module emits fixtures; scaffolds never import from plugin_builder itself
(ADR-0244: emits-never-loads).
"""
from __future__ import annotations

from .base_fixtures import (
    AuditEvent,
    CorvinPluginTestCase,
    HaikuClassifier,
    OpusCheckpointer,
    PluginContext,
    PluginRegistry,
    PluginTestContext,
    plugin_context,
    plugin_registry,
    temp_plugin_home,
)
from .test_runners import (
    PluginTestRunner,
    PluginStructure,
    TestResult,
    run_plugin_tests,
    validate_plugin_structure,
)

__version__ = "2.0.0"

__all__ = [
    "__version__",
    "AuditEvent",
    "CorvinPluginTestCase",
    "HaikuClassifier",
    "OpusCheckpointer",
    "PluginContext",
    "PluginRegistry",
    "PluginStructure",
    "PluginTestContext",
    "PluginTestRunner",
    "TestResult",
    "plugin_context",
    "plugin_registry",
    "run_plugin_tests",
    "temp_plugin_home",
    "validate_plugin_structure",
]
