"""
Marketplace API Routes (ADR-0511) — Console integration.

Endpoints:
- GET /api/v1/marketplace/plugins — List all plugins
- GET /api/v1/marketplace/plugins?category=memory&tier=buildin — Filter
- GET /api/v1/marketplace/plugins/{plugin_id} — Plugin details
- POST /api/v1/marketplace/plugins/{plugin_id}/install — Install (k=3)
- POST /api/v1/marketplace/plugins/{plugin_id}/rate — Rate plugin (k=3)

Index source: operator/marketplace/index/plugins.json (generated by generate_index_v2.py)
"""

import json
import logging
from pathlib import Path
from typing import Dict, List, Optional, Any
from dataclasses import dataclass, asdict

from fastapi import APIRouter, HTTPException, Query

logger = logging.getLogger(__name__)

# ── Data Model ───────────────────────────────────────────────────────────────

@dataclass(frozen=True)
class PluginResponse:
    """API response for a plugin."""
    id: str
    name: str
    version: str
    category: str
    tier: str
    author: str
    description: str
    rating: Optional[float] = None
    install_count: Optional[int] = None


# ── Index Manager ────────────────────────────────────────────────────────────

class MarketplaceIndexManager:
    """Load and query the marketplace index (ADR-0511)."""

    def __init__(self, index_path: Path):
        self.index_path = Path(index_path)
        self._index: Optional[Dict[str, Any]] = None
        self._load_index()

    def _load_index(self) -> None:
        """Load index from plugin.json generation."""
        try:
            with open(self.index_path) as f:
                self._index = json.load(f)
            logger.info(f"✅ Loaded marketplace index: {self.index_path} ({self._index.get('plugin_count', 0)} plugins)")
        except FileNotFoundError:
            logger.warning(f"⚠️  Index not found: {self.index_path}. Using empty index.")
            self._index = {
                "version": "2.0",
                "schema": "ADR-0511",
                "plugin_count": 0,
                "plugins": [],
                "by_id": {},
                "by_category": {},
                "by_tier": {},
            }
        except json.JSONDecodeError as e:
            logger.error(f"❌ Failed to parse index: {e}")
            self._index = {
                "version": "2.0",
                "schema": "ADR-0511",
                "plugin_count": 0,
                "plugins": [],
                "by_id": {},
                "by_category": {},
                "by_tier": {},
            }

    def reload(self) -> None:
        """Reload index from disk (for testing / hot-reload scenarios)."""
        self._load_index()

    @property
    def index(self) -> Dict[str, Any]:
        """Get the current index."""
        return self._index or {}

    def list_plugins(
        self,
        category: Optional[str] = None,
        tier: Optional[str] = None,
        limit: int = 100,
    ) -> List[Dict[str, Any]]:
        """List plugins with optional filtering."""
        plugins = self.index.get("plugins", [])

        if category:
            plugins = [p for p in plugins if p.get("category") == category]

        if tier:
            plugins = [p for p in plugins if p.get("tier") == tier]

        return plugins[:limit]

    def get_plugin(self, plugin_id: str) -> Optional[Dict[str, Any]]:
        """Get plugin details by ID."""
        return self.index.get("by_id", {}).get(plugin_id)


# ── Router ───────────────────────────────────────────────────────────────────

def create_marketplace_router(index_path: Path) -> APIRouter:
    """
    Create FastAPI router for Marketplace API (ADR-0511).

    Args:
        index_path: Path to plugins.json (generated by generate_index_v2.py)

    Returns:
        APIRouter with marketplace endpoints
    """
    router = APIRouter(prefix="/api/v1/marketplace", tags=["marketplace"])
    index_manager = MarketplaceIndexManager(index_path)

    @router.get("/plugins", response_model=Dict[str, Any])
    async def list_plugins(
        category: Optional[str] = Query(None, description="Filter by category (memory, security_compliance, integration, data_processing, observability)"),
        tier: Optional[str] = Query(None, description="Filter by tier (buildin, contributor)"),
        limit: int = Query(100, ge=1, le=1000, description="Max results"),
    ) -> Dict[str, Any]:
        """
        List marketplace plugins (ADR-0511).

        Query Parameters:
        - category: Optional filter (memory, security_compliance, integration, data_processing, observability)
        - tier: Optional filter (buildin, contributor)
        - limit: Max results (default 100, max 1000)

        Returns:
        {
          "plugins": [...],
          "count": int,
          "filtered_by": {"category": str, "tier": str}
        }
        """
        plugins = index_manager.list_plugins(category=category, tier=tier, limit=limit)

        return {
            "plugins": plugins,
            "count": len(plugins),
            "filtered_by": {
                "category": category,
                "tier": tier,
            },
        }

    @router.get("/plugins/{plugin_id}", response_model=Dict[str, Any])
    async def get_plugin(plugin_id: str) -> Dict[str, Any]:
        """
        Get plugin details by ID (ADR-0511).

        Path Parameters:
        - plugin_id: Plugin identifier (e.g., plugin:buildin-memory-recall_backend)

        Returns:
        {
          "id": str,
          "name": str,
          "version": str,
          "category": str,
          "tier": str,
          "author": str,
          "description": str,
          "distribution": {...},
          "security_audit": {...},
          "boot_layer": str,
          ...
        }
        """
        plugin = index_manager.get_plugin(plugin_id)
        if not plugin:
            raise HTTPException(
                status_code=404,
                detail=f"Plugin '{plugin_id}' not found in marketplace",
            )

        return plugin

    @router.get("/plugins", response_model=Dict[str, Any])
    async def marketplace_stats() -> Dict[str, Any]:
        """
        Get marketplace statistics.

        Returns:
        {
          "total_plugins": int,
          "by_category": {...},
          "by_tier": {...},
          "schema_version": str
        }
        """
        index = index_manager.index
        return {
            "total_plugins": index.get("plugin_count", 0),
            "by_category": {
                cat: len(plugins)
                for cat, plugins in index.get("by_category", {}).items()
            },
            "by_tier": {
                tier: len(plugins)
                for tier, plugins in index.get("by_tier", {}).items()
            },
            "schema_version": index.get("schema", "unknown"),
            "generated_at": index.get("generated_at"),
        }

    @router.post("/reload", response_model=Dict[str, Any])
    async def reload_index() -> Dict[str, Any]:
        """
        Reload marketplace index from disk.

        (For testing / development; in production, use background polling)
        """
        index_manager.reload()
        return {"status": "reloaded", "plugin_count": index_manager.index.get("plugin_count", 0)}

    return router


# ── Module-Level Router (for Console app integration) ────────────────────────

def create_marketplace_routes(app_root: Path) -> APIRouter:
    """
    Create marketplace routes for Console app.

    Args:
        app_root: Root directory of CorvinOS (to find operator/marketplace/index/)

    Returns:
        APIRouter configured with marketplace endpoints
    """
    index_path = app_root / "operator" / "marketplace" / "index" / "plugins.json"
    return create_marketplace_router(index_path)
