"""
Console Marketplace API (ADR-0511) — FastAPI Edition.

Serves the marketplace index (operator/marketplace/index/plugins.json)
generated by operator/marketplace/generate_index_v2.py.

Routes:
  GET  /api/v1/marketplace/plugins            → List all plugins
  GET  /api/v1/marketplace/plugins?category=X → Filter by category
  GET  /api/v1/marketplace/plugins/{id}       → Get one plugin
  POST /api/v1/marketplace/plugins/{id}/install → Install (k=3)

**Migration:** This replaces the old PluginMarketplace backend (ADR-0385).
The new source of truth is JSON manifests (plugin.json) in operator/marketplace/.
"""

import json
import logging
from pathlib import Path
from typing import Optional, Dict, Any

from fastapi import APIRouter, HTTPException, Query

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/api/v1/marketplace", tags=["marketplace"])


class _IndexManager:
    """Manages marketplace index loading and caching."""

    def __init__(self):
        self._index: Optional[Dict[str, Any]] = None
        self._index_path: Optional[Path] = None

    def set_index_path(self, path: Path) -> None:
        """Set the path to plugins.json."""
        self._index_path = Path(path)
        self._index = None  # Invalidate cache

    def get_index(self) -> Dict[str, Any]:
        """Load and cache the marketplace index."""
        if self._index is not None:
            return self._index

        if self._index_path is None:
            # Default path
            self._index_path = Path.cwd() / "operator" / "marketplace" / "index" / "plugins.json"

        try:
            with open(self._index_path) as f:
                self._index = json.load(f)
            logger.info(f"✅ Loaded marketplace index from {self._index_path}")
            return self._index
        except FileNotFoundError:
            logger.warning(f"⚠️  Index not found at {self._index_path}")
            return self._empty_index()
        except json.JSONDecodeError as e:
            logger.error(f"❌ Failed to parse index: {e}")
            return self._empty_index()

    @staticmethod
    def _empty_index() -> Dict[str, Any]:
        return {
            "version": "2.0",
            "schema": "ADR-0511",
            "plugin_count": 0,
            "plugins": [],
            "by_id": {},
            "by_category": {},
            "by_tier": {},
        }


_index_manager = _IndexManager()


def set_marketplace_index_path(path: Path) -> None:
    """Configure the marketplace index path (call from console app)."""
    _index_manager.set_index_path(path)


@router.get("/plugins")
async def list_plugins(
    category: Optional[str] = Query(None),
    tier: Optional[str] = Query(None),
    limit: int = Query(100, ge=1, le=1000),
) -> Dict[str, Any]:
    """
    List marketplace plugins with optional filtering.

    Query Parameters:
    - category: Filter by category (memory, security_compliance, integration, data_processing, observability)
    - tier: Filter by tier (buildin, contributor)
    - limit: Max results (default 100, max 1000)

    Returns:
    {
      "plugins": [...],
      "count": int,
      "filtered_by": {"category": str, "tier": str}
    }
    """
    index = _index_manager.get_index()
    plugins = index.get("plugins", [])

    # Apply filters
    if category:
        plugins = [p for p in plugins if p.get("category") == category]
    if tier:
        plugins = [p for p in plugins if p.get("tier") == tier]

    # Apply limit
    plugins = plugins[:limit]

    return {
        "plugins": plugins,
        "count": len(plugins),
        "filtered_by": {
            "category": category,
            "tier": tier,
        },
    }


@router.get("/plugins/{plugin_id}")
async def get_plugin(plugin_id: str) -> Dict[str, Any]:
    """
    Get plugin details by ID.

    Path Parameters:
    - plugin_id: Plugin identifier (e.g., plugin:buildin-memory-recall_backend)

    Returns the complete plugin.json manifest (ADR-0511).
    """
    index = _index_manager.get_index()
    plugin = index.get("by_id", {}).get(plugin_id)

    if not plugin:
        raise HTTPException(
            status_code=404,
            detail=f"Plugin '{plugin_id}' not found",
        )

    return plugin


@router.get("/stats")
async def marketplace_stats() -> Dict[str, Any]:
    """
    Get marketplace statistics.

    Returns:
    {
      "total_plugins": int,
      "by_category": {...},
      "by_tier": {...},
      "schema_version": str
    }
    """
    index = _index_manager.get_index()

    return {
        "total_plugins": index.get("plugin_count", 0),
        "by_category": {
            cat: len(plugins)
            for cat, plugins in index.get("by_category", {}).items()
        },
        "by_tier": {
            tier: len(plugins)
            for tier, plugins in index.get("by_tier", {}).items()
        },
        "schema_version": index.get("schema", "unknown"),
        "generated_at": index.get("generated_at"),
    }


@router.post("/reload")
async def reload_index() -> Dict[str, Any]:
    """
    Reload marketplace index from disk (for development/testing).
    """
    _index_manager._index = None  # Invalidate cache
    index = _index_manager.get_index()

    return {
        "status": "reloaded",
        "plugin_count": index.get("plugin_count", 0),
    }


# Phase 3 Installation API (imported from marketplace_install.py)
# Routes: POST /install, /uninstall, PATCH /enable, /disable, GET /progress
# See marketplace_install.py for full implementation
from . import marketplace_install as _install_routes
router.include_router(_install_routes.router)
