"""
Console Marketplace API (ADR-0511) — FastAPI Edition.

Serves the marketplace index (corvin_operator/marketplace/index/plugins.json)
generated by corvin_operator/marketplace/generate_index_v2.py.

Routes:
  GET  /api/v1/marketplace/plugins            → List all plugins
  GET  /api/v1/marketplace/plugins?category=X → Filter by category
  GET  /api/v1/marketplace/plugins/{id}       → Get one plugin
  POST /api/v1/marketplace/plugins/{id}/install → Install (k=3)

**Migration:** This replaces the old PluginMarketplace backend (ADR-0385).
The new source of truth is JSON manifests (plugin.json) in corvin_operator/marketplace/.
"""

import json
import logging
import os
from pathlib import Path
from typing import Optional, Dict, Any

from typing import Annotated

from fastapi import APIRouter, Depends, HTTPException, Query

from .. import audit as console_audit
from .. import auth as session_auth
from ..deps import require_csrf, require_session

logger = logging.getLogger(__name__)

# Security contract (adversarial review E-03, 2026-09-03): every read requires
# a console session; ``POST /reload`` is a mutation → session + CSRF + audit.
# The install sub-router below carries NO prefix of its own — this prefix is
# the only one (it used to be doubled, see marketplace_install.py).
router = APIRouter(prefix="/api/v1/marketplace", tags=["marketplace"])

#: Upper bound for the GitHub index fallback. The real index is ~100 KB; an
#: unbounded ``response.read()`` let a hostile or broken upstream stream an
#: arbitrary amount into memory (and json.loads) inside a request handler.
_MAX_INDEX_BYTES = 8 * 1024 * 1024


class _IndexManager:
    """Manages marketplace index loading and caching."""

    def __init__(self):
        self._index: Optional[Dict[str, Any]] = None
        self._index_path: Optional[Path] = None

    def set_index_path(self, path: Path) -> None:
        """Set the path to plugins.json."""
        self._index_path = Path(path)
        self._index = None  # Invalidate cache

    def get_index(self) -> Dict[str, Any]:
        """Load and cache the marketplace index."""
        if self._index is not None:
            return self._index

        if self._index_path is None:
            self._index_path = resolve_index_path()

        try:
            with open(self._index_path) as f:
                self._index = json.load(f)
            logger.info(f"✅ Loaded marketplace index from {self._index_path}")
            return self._index
        except FileNotFoundError:
            logger.warning(f"⚠️  Index not found at {self._index_path}, fetching from GitHub...")
            # Fallback: fetch from Corvin-Marketplace repo
            try:
                import urllib.request
                url = "https://raw.githubusercontent.com/CorvinLabs/Corvin-Marketplace/main/index/plugins.json"
                with urllib.request.urlopen(url, timeout=5) as response:
                    raw = response.read(_MAX_INDEX_BYTES + 1)
                if len(raw) > _MAX_INDEX_BYTES:
                    raise ValueError(
                        f"remote index exceeds {_MAX_INDEX_BYTES} bytes — refused"
                    )
                self._index = json.loads(raw)
                logger.info(f"✅ Loaded marketplace index from GitHub: {url}")
                return self._index
            except Exception as e:
                logger.error(f"❌ Failed to fetch from GitHub: {e}")
                return self._empty_index()
        except json.JSONDecodeError as e:
            logger.error(f"❌ Failed to parse index: {e}")
            return self._empty_index()

    @staticmethod
    def _empty_index() -> Dict[str, Any]:
        return {
            "version": "2.0",
            "schema": "ADR-0511",
            "plugin_count": 0,
            "plugins": [],
            "by_id": {},
            "by_category": {},
            "by_tier": {},
        }


def resolve_index_path() -> Path:
    """Locate plugins.json.

    The plugin sources were moved out of CorvinOS into the sibling
    Corvin-Marketplace repository (commit 3c691741), so the in-repo path only
    still exists on branches predating that move. Resolution order:

    1. ``CORVIN_MARKETPLACE_INDEX`` — explicit operator override.
    2. ``<cwd>/corvin_operator/marketplace/index/plugins.json`` — legacy in-repo index.
    3. ``<repo parent>/Corvin-Marketplace/index/plugins.json`` — sibling checkout.

    Returns the first candidate that exists; otherwise the legacy path, so the
    caller's FileNotFoundError branch takes over and falls back to GitHub.
    """
    override = os.environ.get("CORVIN_MARKETPLACE_INDEX")
    if override:
        return Path(override).expanduser()

    legacy = Path.cwd() / "corvin_operator" / "marketplace" / "index" / "plugins.json"
    # core/console/corvin_console/routes/marketplace.py -> repo root -> its parent
    repo_root = Path(__file__).resolve().parents[4]
    sibling = repo_root.parent / "Corvin-Marketplace" / "index" / "plugins.json"

    for candidate in (legacy, sibling):
        if candidate.is_file():
            return candidate
    return legacy


_index_manager = _IndexManager()


def set_marketplace_index_path(path: Path) -> None:
    """Configure the marketplace index path (call from console app)."""
    _index_manager.set_index_path(path)


@router.get("/plugins")
async def list_plugins(
    rec: Annotated[session_auth.SessionRecord, Depends(require_session)],
    category: Optional[str] = Query(None),
    tier: Optional[str] = Query(None),
    limit: int = Query(100, ge=1, le=1000),
) -> Dict[str, Any]:
    """
    List marketplace plugins with optional filtering.

    Query Parameters:
    - category: Filter by category (memory, security_compliance, integration, data_processing, observability)
    - tier: Filter by tier (buildin, contributor)
    - limit: Max results (default 100, max 1000)

    Returns:
    {
      "plugins": [...],
      "count": int,
      "filtered_by": {"category": str, "tier": str}
    }
    """
    index = _index_manager.get_index()
    plugins = index.get("plugins", [])

    # Apply filters
    if category:
        plugins = [p for p in plugins if p.get("category") == category]
    if tier:
        plugins = [p for p in plugins if p.get("tier") == tier]

    # Apply limit
    plugins = plugins[:limit]

    # ADR-0892 — every listing carries its LOCAL state, so the console never
    # has to guess: `installable` + `install_blocker` (can this build install
    # it at all — only builtin-tier ids with a plugin.yaml under a trusted root
    # resolve; the index's 3 contributor entries never did, and the old panel
    # offered an Install button that always failed), `registry_id` (the
    # manifest's plugin_id, which is what registry.yaml and /plugins key on —
    # the index id is `plugin:<tier>-<cat>-<name>`), `installed`/`enabled`
    # from the tenant registry, `runtime_loaded` from THIS process.
    installed = _tenant_install_state(rec.tenant_id)
    enriched = [dict(p, **_local_state(p, installed)) for p in plugins]

    return {
        "plugins": enriched,
        "count": len(enriched),
        "filtered_by": {
            "category": category,
            "tier": tier,
        },
    }


# ── Local state join (ADR-0892) ───────────────────────────────────────────

#: index_id -> (registry_id | None, blocker | None); keyed on the index the ids
#: came from so a reload of plugins.json invalidates it.
_RESOLVE_CACHE: Dict[str, tuple[Optional[str], Optional[str]]] = {}
_RESOLVE_CACHE_KEY: Optional[str] = None


def _resolve_index_id(index_id: str) -> tuple[Optional[str], Optional[str]]:
    """``(registry_id, blocker)`` — exactly the resolution the install route
    performs (marketplace_resolve), so "installable" here and "installed" there
    cannot disagree."""
    global _RESOLVE_CACHE_KEY
    from . import marketplace_resolve as _resolve

    key = str((_index_manager.get_index().get("generated_at")) or "")
    if key != _RESOLVE_CACHE_KEY:
        _RESOLVE_CACHE.clear()
        _RESOLVE_CACHE_KEY = key
    hit = _RESOLVE_CACHE.get(index_id)
    if hit is not None:
        return hit
    if not _resolve.available():
        out: tuple[Optional[str], Optional[str]] = (None, "plugin subsystem unavailable in this installation")
    else:
        try:
            out = (_resolve.manifest_plugin_id(index_id), None)
        except _resolve.MarketplaceResolveError as exc:
            out = (None, str(exc))
        except Exception as exc:  # noqa: BLE001 — a broken manifest is a blocker, not a 500
            out = (None, f"manifest unreadable: {type(exc).__name__}")
    _RESOLVE_CACHE[index_id] = out
    return out


def _tenant_install_state(tenant_id: str) -> Dict[str, Dict[str, Any]]:
    """registry_id -> {enabled, runtime_loaded} for this tenant. Empty when the
    plugin subsystem is absent; a corrupt registry is reported by /plugins,
    not hidden here."""
    try:
        from . import plugins as _plugins

        if not _plugins._PLUGINS_AVAILABLE:
            return {}
        registry = _plugins._load(tenant_id)
    except HTTPException:
        return {}
    except Exception:  # noqa: BLE001
        return {}
    out: Dict[str, Dict[str, Any]] = {}
    for pid, rec in registry.records.items():
        loaded, _why = _plugins._runtime_state(pid)
        out[pid] = {"enabled": bool(getattr(rec, "enabled", False)), "runtime_loaded": bool(loaded)}
    return out


def _local_state(entry: Dict[str, Any], installed: Dict[str, Dict[str, Any]]) -> Dict[str, Any]:
    registry_id, blocker = _resolve_index_id(str(entry.get("id") or ""))
    state = installed.get(registry_id) if registry_id else None
    return {
        "registry_id": registry_id,
        "installable": blocker is None,
        "install_blocker": blocker,
        "installed": state is not None,
        "enabled": bool(state and state["enabled"]),
        "runtime_loaded": bool(state and state["runtime_loaded"]),
    }


@router.get("/plugins/{plugin_id}")
async def get_plugin(
    plugin_id: str,
    rec: Annotated[session_auth.SessionRecord, Depends(require_session)],
) -> Dict[str, Any]:
    """
    Get plugin details by ID.

    Path Parameters:
    - plugin_id: Plugin identifier (e.g., plugin:buildin-memory-recall_backend)

    Returns the complete plugin.json manifest (ADR-0511).
    """
    index = _index_manager.get_index()
    plugin = index.get("by_id", {}).get(plugin_id)

    if not plugin:
        raise HTTPException(
            status_code=404,
            detail=f"Plugin '{plugin_id}' not found",
        )

    return plugin


@router.get("/stats")
async def marketplace_stats(
    rec: Annotated[session_auth.SessionRecord, Depends(require_session)],
) -> Dict[str, Any]:
    """
    Get marketplace statistics.

    Returns:
    {
      "total_plugins": int,
      "by_category": {...},
      "by_tier": {...},
      "schema_version": str
    }
    """
    index = _index_manager.get_index()

    return {
        "total_plugins": index.get("plugin_count", 0),
        "by_category": {
            cat: len(plugins)
            for cat, plugins in index.get("by_category", {}).items()
        },
        "by_tier": {
            tier: len(plugins)
            for tier, plugins in index.get("by_tier", {}).items()
        },
        "schema_version": index.get("schema", "unknown"),
        "generated_at": index.get("generated_at"),
    }


@router.post("/reload")
async def reload_index(
    rec: Annotated[session_auth.SessionRecord, Depends(require_csrf)],
) -> Dict[str, Any]:
    """
    Reload marketplace index from disk (for development/testing).
    """
    _index_manager._index = None  # Invalidate cache
    index = _index_manager.get_index()
    console_audit.action_performed(
        tenant_id=rec.tenant_id,
        sid_fingerprint=rec.sid_fingerprint,
        action="marketplace.reload_index",
        target_kind="marketplace_index",
        target_id=str(_index_manager._index_path or "index"),
    )

    return {
        "status": "reloaded",
        "plugin_count": index.get("plugin_count", 0),
    }


# Phase 3 Installation API (imported from marketplace_install.py)
# Routes: POST /install, /uninstall, PATCH /enable, /disable, GET /progress
# See marketplace_install.py for full implementation
from . import marketplace_install as _install_routes
router.include_router(_install_routes.router)
