"""
Console Marketplace API (ADR-0511) — FastAPI Edition.

Serves the marketplace index (operator/marketplace/index/plugins.json)
generated by operator/marketplace/generate_index_v2.py.

Routes:
  GET  /api/v1/marketplace/plugins            → List all plugins
  GET  /api/v1/marketplace/plugins?category=X → Filter by category
  GET  /api/v1/marketplace/plugins/{id}       → Get one plugin
  POST /api/v1/marketplace/plugins/{id}/install → Install (k=3)

**Migration:** This replaces the old PluginMarketplace backend (ADR-0385).
The new source of truth is JSON manifests (plugin.json) in operator/marketplace/.
"""

import json
import logging
from pathlib import Path
from typing import Optional, Dict, Any

from fastapi import APIRouter, HTTPException, Query

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/api/v1/marketplace", tags=["marketplace"])


class _IndexManager:
    """Manages marketplace index loading and caching."""

    def __init__(self):
        self._index: Optional[Dict[str, Any]] = None
        self._index_path: Optional[Path] = None

    def set_index_path(self, path: Path) -> None:
        """Set the path to plugins.json."""
        self._index_path = Path(path)
        self._index = None  # Invalidate cache

    def get_index(self) -> Dict[str, Any]:
        """Load and cache the marketplace index."""
        if self._index is not None:
            return self._index

        if self._index_path is None:
            # Default path
            self._index_path = Path.cwd() / "operator" / "marketplace" / "index" / "plugins.json"

        try:
            with open(self._index_path) as f:
                self._index = json.load(f)
            logger.info(f"✅ Loaded marketplace index from {self._index_path}")
            return self._index
        except FileNotFoundError:
            logger.warning(f"⚠️  Index not found at {self._index_path}")
            return self._empty_index()
        except json.JSONDecodeError as e:
            logger.error(f"❌ Failed to parse index: {e}")
            return self._empty_index()

    @staticmethod
    def _empty_index() -> Dict[str, Any]:
        return {
            "version": "2.0",
            "schema": "ADR-0511",
            "plugin_count": 0,
            "plugins": [],
            "by_id": {},
            "by_category": {},
            "by_tier": {},
        }


_index_manager = _IndexManager()


def set_marketplace_index_path(path: Path) -> None:
    """Configure the marketplace index path (call from console app)."""
    _index_manager.set_index_path(path)


@router.get("/plugins")
async def list_plugins(
    category: Optional[str] = Query(None),
    tier: Optional[str] = Query(None),
    limit: int = Query(100, ge=1, le=1000),
) -> Dict[str, Any]:
    """
    List marketplace plugins with optional filtering.

    Query Parameters:
    - category: Filter by category (memory, security_compliance, integration, data_processing, observability)
    - tier: Filter by tier (buildin, contributor)
    - limit: Max results (default 100, max 1000)

    Returns:
    {
      "plugins": [...],
      "count": int,
      "filtered_by": {"category": str, "tier": str}
    }
    """
    index = _index_manager.get_index()
    plugins = index.get("plugins", [])

    # Apply filters
    if category:
        plugins = [p for p in plugins if p.get("category") == category]
    if tier:
        plugins = [p for p in plugins if p.get("tier") == tier]

    # Apply limit
    plugins = plugins[:limit]

    return {
        "plugins": plugins,
        "count": len(plugins),
        "filtered_by": {
            "category": category,
            "tier": tier,
        },
    }


@router.get("/plugins/{plugin_id}")
async def get_plugin(plugin_id: str) -> Dict[str, Any]:
    """
    Get plugin details by ID.

    Path Parameters:
    - plugin_id: Plugin identifier (e.g., plugin:buildin-memory-recall_backend)

    Returns the complete plugin.json manifest (ADR-0511).
    """
    index = _index_manager.get_index()
    plugin = index.get("by_id", {}).get(plugin_id)

    if not plugin:
        raise HTTPException(
            status_code=404,
            detail=f"Plugin '{plugin_id}' not found",
        )

    return plugin


@router.get("/stats")
async def marketplace_stats() -> Dict[str, Any]:
    """
    Get marketplace statistics.

    Returns:
    {
      "total_plugins": int,
      "by_category": {...},
      "by_tier": {...},
      "schema_version": str
    }
    """
    index = _index_manager.get_index()

    return {
        "total_plugins": index.get("plugin_count", 0),
        "by_category": {
            cat: len(plugins)
            for cat, plugins in index.get("by_category", {}).items()
        },
        "by_tier": {
            tier: len(plugins)
            for tier, plugins in index.get("by_tier", {}).items()
        },
        "schema_version": index.get("schema", "unknown"),
        "generated_at": index.get("generated_at"),
    }


@router.post("/reload")
async def reload_index() -> Dict[str, Any]:
    """
    Reload marketplace index from disk (for development/testing).
    """
    _index_manager._index = None  # Invalidate cache
    index = _index_manager.get_index()

    return {
        "status": "reloaded",
        "plugin_count": index.get("plugin_count", 0),
    }

                    "version": "1.0",
                    "last_updated": "2026-08-30T00:00:00Z",
                    "extensions": cached_data,
                    "cached": True,
                }

        # Cache miss or no cache manager: fetch from backend
        marketplace = PluginMarketplace()
        plugins = marketplace.list_plugins(limit=_CATALOG_LIMIT)
        serialized = [serialize_plugin(p) for p in plugins]

        # Update cache
        if cache:
            cache.set(serialized)

        return {
            "version": "1.0",
            "last_updated": "2026-08-30T00:00:00Z",
            "extensions": serialized,
            "cached": False,
        }

    except HTTPException:
        raise
    except Exception as e:
        logger.error(f"Failed to fetch marketplace index: {e}")

        # Stale-while-revalidate: return stale cache on error
        cache = get_cache_manager()
        if cache:
            stale_data = cache.get_stale()
            if stale_data:
                logger.info("Returning stale cache on error")
                return {
                    "version": "1.0",
                    "extensions": stale_data,
                    "cached": True,
                    "stale": True,
                    "error": str(e),
                }

        raise HTTPException(status_code=500, detail=str(e))


@router.get("/search")
async def marketplace_search(
    q: Optional[str] = Query(None),
    category: Optional[str] = Query(None),
    origin: Optional[str] = Query(None),
    rating_min: Optional[float] = Query(None),
    sort: Optional[str] = Query("rating"),
) -> Dict[str, Any]:
    """
    GET /marketplace/search

    Query params:
      q: string (search by name/description)
      category: string (Authentication, Performance, Security, ...)
      origin: string (builtin, vetted, community)
      rating_min: float (1.0-5.0)
      sort: string (rating, downloads, name)

    Returns: {extensions: [filtered results]}
    """
    if not PluginMarketplace:
        raise HTTPException(status_code=503, detail="Marketplace backend unavailable")

    try:
        # Fetch from backend
        marketplace = PluginMarketplace()
        plugins = marketplace.list_plugins(limit=_CATALOG_LIMIT)

        # Client-side filtering
        filtered = plugins
        if q:
            q_lower = q.lower()
            filtered = [
                p
                for p in filtered
                if q_lower in p.name.lower() or q_lower in p.description.lower()
            ]
        if category:
            filtered = [p for p in filtered if p.category.value == category]
        if origin:
            filtered = [p for p in filtered if p.origin.value == origin]
        if rating_min:
            filtered = [p for p in filtered if p.rating_average >= rating_min]

        return {"extensions": [serialize_plugin(p) for p in filtered]}

    except ValueError as e:
        raise HTTPException(status_code=400, detail=f"Invalid query params: {e}")
    except Exception as e:
        logger.error(f"Search failed: {e}")
        raise HTTPException(status_code=500, detail=str(e))


@router.get("/extension/{extension_id}")
async def marketplace_extension_details(extension_id: str) -> Dict[str, Any]:
    """
    GET /marketplace/extension/{id}

    Returns: {
      "id": "auth-saml-2.1",
      "metadata": {...},
      "readme_url": "https://raw.../README.md"
    }

    Error: 404 (not found), 500 (backend error)
    """
    if not PluginMarketplace:
        raise HTTPException(status_code=503, detail="Marketplace backend unavailable")

    try:
        marketplace = PluginMarketplace()
        plugin = marketplace.get_plugin(extension_id)
        if not plugin:
            raise HTTPException(status_code=404, detail=f"Extension '{extension_id}' not found")

        return {
            "id": plugin.plugin_id,
            "metadata": serialize_plugin(plugin),
            "readme_url": (
                f"{plugin.repository_url}/blob/main/README.md"
                if plugin.repository_url
                else None
            ),
        }

    except HTTPException:
        raise
    except Exception as e:
        logger.error(f"Failed to get extension {extension_id}: {e}")
        raise HTTPException(status_code=500, detail=str(e))


@router.post("/install")
async def marketplace_install(body: Dict[str, Any]) -> Dict[str, Any]:
    """
    POST /marketplace/install

    Body: {
      "extension_id": "plugin:example-plugin",
      "version": "0.1.0",
      "tenant_id": "default"
    }

    Returns: {
      "status": "queued",
      "job_id": "install-abc123"
    }

    Note: Phase 1 is mock. Phase 3 will implement actual installation.
    """
    if not PluginMarketplace:
        raise HTTPException(status_code=503, detail="Marketplace backend unavailable")

    try:
        if not body:
            raise HTTPException(status_code=400, detail="Request body required")

        extension_id = body.get("extension_id")
        version = body.get("version")
        tenant_id = body.get("tenant_id", "default")

        if not extension_id:
            raise HTTPException(status_code=400, detail="extension_id required")

        # Validate extension exists
        marketplace = PluginMarketplace()
        plugin = marketplace.get_plugin(extension_id)
        if not plugin:
            raise HTTPException(status_code=404, detail=f"Extension '{extension_id}' not found")

        # Mock job_id
        job_id = f"install-{extension_id}-{version or plugin.version}"

        return {
            "status": "queued",
            "job_id": job_id,
        }

    except HTTPException:
        raise
    except Exception as e:
        logger.error(f"Install failed: {e}")
        raise HTTPException(status_code=500, detail=str(e))


@router.post("/uninstall")
async def marketplace_uninstall(body: Dict[str, Any]) -> Dict[str, Any]:
    """
    POST /marketplace/uninstall

    Body: {
      "extension_id": "plugin:example-plugin",
      "tenant_id": "default"
    }

    Returns: {
      "status": "queued",
      "job_id": "uninstall-abc123"
    }
    """
    if not PluginMarketplace:
        raise HTTPException(status_code=503, detail="Marketplace backend unavailable")

    try:
        if not body:
            raise HTTPException(status_code=400, detail="Request body required")

        extension_id = body.get("extension_id")
        tenant_id = body.get("tenant_id", "default")

        if not extension_id:
            raise HTTPException(status_code=400, detail="extension_id required")

        # Validate extension exists
        marketplace = PluginMarketplace()
        plugin = marketplace.get_plugin(extension_id)
        if not plugin:
            raise HTTPException(status_code=404, detail=f"Extension '{extension_id}' not found")

        job_id = f"uninstall-{extension_id}"

        return {"status": "queued", "job_id": job_id}

    except HTTPException:
        raise
    except Exception as e:
        logger.error(f"Uninstall failed: {e}")
        raise HTTPException(status_code=500, detail=str(e))


@router.patch("/extension/{extension_id}/enable")
async def marketplace_enable(extension_id: str, body: Optional[Dict[str, Any]] = None) -> Dict[str, Any]:
    """
    PATCH /marketplace/extension/{id}/enable

    Body: {"tenant_id": "default"}

    Returns: {"status": "enabled"}

    Note: Phase 1 is mock. Phase 4 will implement actual enable logic.
    """
    if not PluginMarketplace:
        raise HTTPException(status_code=503, detail="Marketplace backend unavailable")

    try:
        # Validate extension exists
        marketplace = PluginMarketplace()
        plugin = marketplace.get_plugin(extension_id)
        if not plugin:
            raise HTTPException(status_code=404, detail=f"Extension '{extension_id}' not found")

        return {"status": "enabled"}

    except HTTPException:
        raise
    except Exception as e:
        logger.error(f"Enable failed: {e}")
        raise HTTPException(status_code=500, detail=str(e))


@router.patch("/extension/{extension_id}/disable")
async def marketplace_disable(extension_id: str, body: Optional[Dict[str, Any]] = None) -> Dict[str, Any]:
    """
    PATCH /marketplace/extension/{id}/disable

    Body: {"tenant_id": "default"}

    Returns: {"status": "disabled"}

    Note: Phase 1 is mock. Phase 4 will implement actual disable logic.
    """
    if not PluginMarketplace:
        raise HTTPException(status_code=503, detail="Marketplace backend unavailable")

    try:
        # Validate extension exists
        marketplace = PluginMarketplace()
        plugin = marketplace.get_plugin(extension_id)
        if not plugin:
            raise HTTPException(status_code=404, detail=f"Extension '{extension_id}' not found")

        return {"status": "disabled"}

    except HTTPException:
        raise
    except Exception as e:
        logger.error(f"Disable failed: {e}")
        raise HTTPException(status_code=500, detail=str(e))


@router.get("/installed")
async def marketplace_installed() -> Dict[str, Any]:
    """
    GET /api/v2/marketplace/installed

    Returns list of installed plugins from ~/.corvin/tenants/_default/plugins/installed/

    Returns:
    {
      "extensions": [
        {
          "plugin_id": "slack-notifier",
          "name": "Slack Notifier",
          "version": "1.0.0",
          "status": "active|inactive",
          "installed_at": "2026-08-31T14:00:00Z"
        },
        ...
      ]
    }

    Error: 500 (backend error)
    """
    try:
        from pathlib import Path

        installed_dir = Path.home() / ".corvin/tenants/_default/plugins/installed"
        extensions = []

        if installed_dir.exists():
            for plugin_dir in installed_dir.iterdir():
                if plugin_dir.is_dir():
                    # Try to read plugin.json for metadata
                    plugin_json = plugin_dir / "plugin.json"
                    metadata = {}

                    if plugin_json.exists():
                        import json
                        with open(plugin_json) as f:
                            metadata = json.load(f)

                    extensions.append({
                        "plugin_id": metadata.get("id", plugin_dir.name),
                        "name": metadata.get("name", plugin_dir.name.replace("-", " ").title()),
                        "version": metadata.get("version", "1.0.0"),
                        "category": metadata.get("category", "Unknown"),
                        "status": "active",
                        "installed_at": "2026-08-31T00:00:00Z",
                    })

        return {
            "extensions": extensions,
            "total": len(extensions),
        }

    except Exception as e:
        logger.error(f"Failed to list installed plugins: {e}")
        raise HTTPException(status_code=500, detail="Failed to retrieve installed plugins")


@router.get("/install/{job_id}/progress")
async def marketplace_install_progress(job_id: str) -> Dict[str, Any]:
    """
    GET /api/v2/marketplace/install/{job_id}/progress

    Poll installation progress. Returns:
    {
      "status": "pending|in_progress|completed|failed",
      "progress": 0-100,
      "message": "Status message (no PII per ADR-0297)"
    }

    Error: 404 (job not found), 500 (backend error)

    Note: Phase 3 stub. Phase 3b will implement real job tracking.
    """
    try:
        # Stub: Return mock progress based on job_id
        # In reality, this would query a job queue (celery, etc.)

        # Mock: Assume job is "in_progress"
        return {
            "status": "in_progress",
            "progress": 75,
            "message": "Installation in progress"
        }

    except Exception as e:
        logger.error(f"Progress polling error: {e}")
        raise HTTPException(status_code=500, detail="Failed to get installation progress")
